### PR TITLE
Unexpected write error #1300

### LINKED ISSUE #1300: Unexpected write error
image

Quota seems to be ok and I have write permissions.
On a related note, the icon in the dialog looks like a close button.

### PR DESCRIPTION
**Pull request by ndt93**
Fixes #1300 

Propagates exceptions when replace labels, replace milestones or edit issue state failed so that more informative error message can be displayed.

### CODE REVIEW

**Comment by ndt93** [comment]
@dariusf Can you help review this? Thanks.

File: src/main/java/backend/Logic.java [hunk 1]
```diff
@@ -264,9 +265,20 @@ public Model getRepo(String repoId) {
...
+        updateIssueLabelsOnServer(issue, newLabels)
+                .exceptionally((e) -> {
+                    result.completeExceptionally(e);
+                    return false;
+                })
                 .thenCombine(localLabelsReplaceFuture, (isUpdateSuccessful, locallyModifiedIssue) ->
-                        handleIssueLabelsUpdateResult(isUpdateSuccessful, locallyModifiedIssue, originalLabels));
+                        handleIssueLabelsUpdateResult(isUpdateSuccessful, locallyModifiedIssue, originalLabels))
+                .thenAccept((isReplacementSuccessful) -> {
+                    if (!result.isCompletedExceptionally()) {
```
Comment (dariusf) [inline src/main/java/backend/Logic.java]: This part is a bit confusing -- we propagate failure using `completeExceptionally` above as well as with a boolean value. It's not clear what the difference between the two is from just reading this part. Is there a way to simplify it, like maybe `completeExceptionally` only at the end if `isReplacementSuccessful` is false?

File: src/main/java/undo/UndoController.java [hunk 2]
```diff
@@ -73,6 +77,11 @@ private boolean handleActionResult(TurboIssue issue, Action<TurboIssue> action,
         return success;
     }
 
+    private boolean handleActionException(TurboIssue issue, Action<TurboIssue> action, Throwable exception) {
+        showErrorDialog(issue, action, Utility.removeFirstWord(exception.getMessage()));
```
Comment (dariusf) [inline src/main/java/undo/UndoController.java]: Maybe we can add a comment here saying what exception messages look like, and what the intended output is. Also, I'm not sure if messages are consistent across exception types. Might need a regex.

File: src/test/java/tests/LogicTests.java [hunk 3]
```diff
@@ -88,6 +88,18 @@ public void replaceIssueMilestone_repoIOFails_unsuccessful() throws ExecutionExc
     }
 
     /**
+     * Tests that replaceIssueMilestone propagates exceptions when repoIO encounter exceptions
+     */
+    @Test(expected = ExecutionException.class)
```
Comment (dariusf) [inline src/test/java/tests/LogicTests.java]: We can use [ExpectedException](https://github.com/HubTurbo/HubTurbo/blob/b20957b3c5f6d99901ab38c8ff21e67092c3464f/src/test/java/tests/CollaboratorServiceExTests.java#L38-L42) here. Think that's what we're supposed to standardise on.

File: src/main/java/backend/Logic.java (hunk 1 above)
Comment (ndt93) [inline src/main/java/backend/Logic.java]: There are two `Futures` here because we want to handle the exception both in `Logic` (reverting to the previous labels) and then still propagate it to the `UI` (`exceptionally` will end the exception propagation). That's the also the reason why the `exceptionally` is put in the middle. I will see how this can be made clearer.

**Comment by ndt93** [comment]
@dariusf I've made some changes. You can review this again.

**Comment by dariusf** [comment]
Nice work. Last thing: `handleActionException` isn't covered, and it seems like it needs a UI test. 😛 Is it worth covering?

**Comment by ndt93** [comment]
Yeah, we should probably cover that T.T

**Comment by ndt93** [comment]
@dariusf Covered the method with a UI test. You can check this again.
