### PR TITLE
'-label:p.' does not match issues without label group 'p' #903

### LINKED ISSUE #903: '-label:p.' does not match issues without label group 'p'
In TEAMMATES, priority labels are given as `p.*`. I was trying to use `-label:p.` to find issues without a priority, but it did not work.

### PR DESCRIPTION
**Pull request by dariusf**
Fixes #903.

### CODE REVIEW

File: src/test/java/tests/FilterEvalTests.java [hunk 1]
```diff
@@ -158,6 +156,22 @@ public void label() {
         } catch (ParseException ignored) {
         }
 
+        // Ensure that early termination does not occur
```
Comment (acruis) [inline src/test/java/tests/FilterEvalTests.java]: Unfortunately, without the commit message, it took me a while to figure out what the "early termination" refers to (I thought it was early termination of the `label()` test at first, but that didn't make sense).

Is it possible to clarify that this refers to the new `labelsSatisfy` loop?

Comment (dariusf) [inline src/test/java/tests/FilterEvalTests.java]: Sure, done. Also added a comment to `labelsSatisfy` to explain the approach.

**Comment by acruis** [comment]
OK, good to merge.
