### PR TITLE
Fix unexpected behaviour when parsing number in quotes #1194

### LINKED ISSUE #1194: Fix parser not parsing number in quote as string
Causes filter expression to return false when matching with issue. For example: 

- I have an issue with body that contains the string `normalize output into (0 - 255)`.
- Filter expression: `body:"0"`

### PR DESCRIPTION
**Pull request by jinified**
Fixes #1194

### CODE REVIEW

**Comment by jinified** [comment]
ready for review @dariusf

**Comment by dariusf** [comment]
Hmm, this may not be the best fix. For one, `allowMultipleKeywords` in that method will never be true, so [this case](https://github.com/jinified/HubTurbo/blob/1194-fix-parsing-of-content-in-quote/src/main/java/filter/Parser.java#L210) will never be entered.

The fix I was thinking of was to move all the quote-handling from the parser to the lexer. That way quoted strings are parsed as a single token, and we can just check for that here, without having to consume tokens in a loop.

**Comment by jinified** [comment]
@dariusf  should we change the TokenType of QUOTE -> QUOTED_CONTENT since one token is essentially includes not only the quote.

**Comment by dariusf** [comment]
Yes, that would be good.

**Comment by jinified** [comment]
ready for review @dariusf

File: src/main/java/filter/lexer/Lexer.java [hunk 1]
```diff
@@ -26,7 +26,7 @@
 
             new Rule("\\(", TokenType.LBRACKET),
             new Rule("\\)", TokenType.RBRACKET),
-            new Rule("\\\"", TokenType.QUOTE),
+            new Rule(".*\\\"(.*)\\\".*", TokenType.QUOTED_CONTENT),
```
Comment (dariusf) [inline src/main/java/filter/lexer/Lexer.java]: Hmm, this is a bit too permissive. Right now things like `body:@#$%^"is"` pass tests. Try to match the smallest possible set of strings which constitute 'something that's quoted'. For example, we probably don't want to allow `"""` (which also works now).

More tests for this would also be nice.

File: src/main/java/filter/Parser.java [hunk 2]
```diff
@@ -107,18 +106,10 @@ private FilterExpression parseExpression(int precedence) {
...
-
-    private FilterExpression parseQuotedContent(QualifierType type) {
-        StringBuilder sb = new StringBuilder();
-        while (!isQuoteToken(lookAhead())) {
-            sb.append(consume().getValue()).append(' ');
-        }
-        return new Qualifier(type, sb.toString().trim());
+    private FilterExpression parseQuotedContent(QualifierType type, Token token) {
+        String keywords = token.getValue();
+        keywords = keywords.substring(1, keywords.length() - 1);
```
Comment (dariusf) [inline src/main/java/filter/Parser.java]: Instead of this (which doesn't always remove the correct characters), we can use `Utility.stripQuotes` and `trim`.

File: src/main/java/filter/Parser.java [hunk 3]
```diff
@@ -223,7 +206,7 @@ private boolean isKeywordToken(Token token) {
     }
 
     private boolean isQuoteToken(Token token) {
-        return token.getType() == TokenType.QUOTE;
+        return token.getType() == TokenType.QUOTED_CONTENT;
```
Comment (dariusf) [inline src/main/java/filter/Parser.java]: This method name can be updated, to be more specific.

**Comment by jinified** [comment]
@dariusf  I have been thinking about the pattern for a quoted content. My approach is to whitelist a character instead of simply negating a symbol such as ". Though this is more restrictive, considering the use case, not may users would match symbol such as "?" , "[" , "]". However, it will still permit whitespace char so "     " is will be matched.

**Comment by dariusf** [comment]
Both have upsides and downsides. Users may want to quote characters which are normally taken as syntax, e.g. `a:":"`, so these should be allowed.

If the regex ends up duplicating all the others, it may be better to go with the negation approach, but otherwise being more restrictive is fine.

**Comment by jinified** [comment]
ready for review

File: src/main/java/filter/lexer/Lexer.java [hunk 4]
```diff
@@ -26,7 +26,7 @@
 
             new Rule("\\(", TokenType.LBRACKET),
             new Rule("\\)", TokenType.RBRACKET),
-            new Rule("\\\"", TokenType.QUOTE),
+            new Rule("\\\"([^(\\\")]+)\\\"", TokenType.QUOTED_CONTENT),
```
Comment (dariusf) [inline src/main/java/filter/lexer/Lexer.java]: The parentheses around the `[...]+` are unnecessary I think, because this simple lexer doesn't use capturing groups.

Are the parentheses inside necessary? Did you intend to disallow `label:"(abc)"`?

Comment (jinified) [inline src/main/java/filter/lexer/Lexer.java]: Nope

Comment (dariusf) [inline src/main/java/filter/lexer/Lexer.java]: Just noticed: escaping inside the `[]` may be unnecessary as well.

Comment (jinified) [inline src/main/java/filter/lexer/Lexer.java]: Is it because inside the [ ] it will just matches the character itself right ?

Comment (jinified) [inline src/main/java/filter/lexer/Lexer.java]: This is because inside the [ ] it will just match the character right ?

Comment (dariusf) [inline src/main/java/filter/lexer/Lexer.java]: Yes. Actually... `new Rule("\"[^\"]+\"", ...)` will work. The escaping from before was redundant. :stuck_out_tongue:

**Comment by dariusf** [comment]
Same, are the tests adequate here? Seeing as coverage isn't green.

**Comment by jinified** [comment]
I have tested different cases for parsing content in quotes.

File: src/main/java/filter/lexer/Lexer.java [hunk 5]
```diff
@@ -26,7 +26,7 @@
 
             new Rule("\\(", TokenType.LBRACKET),
             new Rule("\\)", TokenType.RBRACKET),
-            new Rule("\\\"", TokenType.QUOTE),
+            new Rule("\\\"[^\"]+\\\"", TokenType.QUOTED_CONTENT),
```
Comment (dariusf) [inline src/main/java/filter/lexer/Lexer.java]: The escaping for the surrounding quotes is not needed. This can be simplified to `new Rule("\"[^\"]+\"", ...)`.

**Comment by dariusf** [comment]
Looks like the coverage drop is a false positive. No more comments from me.
