### PR TITLE
Ctrl+R doesn't work if the focus is on the repo dropdown #962

### LINKED ISSUE #846: Document 'change repo' keyboard shortcut
Can be documented under the 'Control panel view' section.
The shortcut is Ctrl+R

### LINKED ISSUE #962: Ctrl+R doesn't work if the focus is on the repo dropdown
As per title

### PR DESCRIPTION
**Pull request by HansNewbie**
Fixes #962, fixes #846

### CODE REVIEW

**Comment by HansNewbie** [comment]
@damithc this PR is regarding Ctrl+R on repo dropdown. I have a few clarifications needed:
- Currently if you press `Esc` on repo dropdown, the focus is on the bar above the panel, hence all panel shortcut will not work. Would you like to keep it this way or if `Esc` is pressed the focus should return to panel?
- On pressing `Ctrl+R`, I will just put the cursor at the end of the repo name. Is that alright, or would you like focus to be transferred back to panel?

I will update the keyboard shortcut documentation about `Ctrl+R` and create a test case for `Ctrl+R` on repo dropdown soon.

**Comment by dariusf** [comment]
I added the documentation issue to the description.

**Comment by dariusf** [comment]
Actually I'm not sure we should duplicate the hotkey binding here. Would it be possible to bind Ctrl+R globally, by registering it [on the scene](http://stackoverflow.com/a/25421376)?

File: src/main/java/ui/UI.java [hunk 1]
```diff
@@ -294,6 +299,14 @@ private void setupMainStage(Scene scene) {
         mainStage.hide();
     }
 
+    private void setupGlobalKeyboardShortcut(Scene scene) {
```
Comment (HansNewbie) [inline src/main/java/ui/UI.java]: @dariusf Something like this?

Comment (dariusf) [inline src/main/java/ui/UI.java]: Yup!

File: src/test/java/guitests/KeyboardShortcutsTest.java [hunk 2]
```diff
@@ -144,15 +144,48 @@ public void keyboardShortcutsTest() {
...
+        PlatformEx.waitOnFxThread();
+        assertEquals(2, repoSelectorComboBox.getItems().size());
+        assertEquals(repoSelectorComboBox.getValue(), "dummy1/dummy1");
+        // test shortcut on repo dropdown
+        doubleClick(repoSelectorComboBox);
+        press(KeyCode.CONTROL).press(KeyCode.R).release(KeyCode.R).release(KeyCode.CONTROL);
+        PlatformEx.waitOnFxThread();
+        push(KeyCode.ESCAPE);
+        PlatformEx.waitOnFxThread();
+        assertEquals(repoSelectorComboBox.getValue(), "dummy/dummy");
```
Comment (HansNewbie) [inline src/test/java/guitests/KeyboardShortcutsTest.java]: @dariusf I got a problem here. Altho it passes locally and also on manual testing everything was good, this case always fails in Travis. In Travis, `Ctrl+R` does not work on repo dropdown but it works on panels. Any guess on why and what I could do about it?

I tried several things:
  - `PlatformEx.waitOnFxThread()` - you can say I spam it since even without any of those the test would pass locally
  - `sleep(1000)` - didn't work
  - press `Esc` after `Ctrl+R` on repo dropdown (in the hope that it will update) - didn't work

Comment (dariusf) [inline src/test/java/guitests/KeyboardShortcutsTest.java]: Possible causes... the event handler could not be bound, but that's unlikely.

Try using the new `pushKeys` method on the KeyCodeCombination directly. Another possibility is to wait until isFocused() returns true (UITest.waitUntil).

Comment (HansNewbie) [inline src/test/java/guitests/KeyboardShortcutsTest.java]: @dariusf I tried to check if the key press works on Travis (by printing out some message on the keypress event) and it works.

I tried `pushKeys`, same result, does not work on repo dropdown. I am not sure what you mean with isFocused() but let me try it.

Comment (dariusf) [inline src/test/java/guitests/KeyboardShortcutsTest.java]: Something like [this](https://github.com/HubTurbo/HubTurbo/blob/master/src/test/java/guitests/UITest.java#L226)? I don't know whether the problem is that the repo dropdown is not in focus when the key press event happens though.

Anyway pushKeys is preferred to press/push. More convenient and there is less chance of problems with timing issues.

Comment (HansNewbie) [inline src/test/java/guitests/KeyboardShortcutsTest.java]: Since the keyboard shortcut is global, where the focus is should not matter, right? Then do I still need wait until is focused?

On pushKeys, apparently platformEx.waitOnThread did not work. It will fail locally. I tried using sleep for now just to see if it works on Travis with pushKeys.

**Comment by HansNewbie** [comment]
@dariusf should I just revert back to putting the shortcut in the panels and selector box instead of making it global? Or should I not put the failing test case (bad idea, but I don't think there is any workaround)?

**Comment by dariusf** [comment]
Revert I guess, and leave a comment there saying why it's duplicated.

**Comment by HansNewbie** [comment]
Noted

**Comment by dariusf** [comment]
Thanks for exploring it! So this PR will now only bind the key in the repo dropdown, and update the docs, right?

**Comment by HansNewbie** [comment]
And also test cases. Originally `Ctrl+R` has no test cases at all.

And I think I figure out why Travis keeps failing at the test. It seems `Ctrl+R` on repo dropdown is non-deterministic. I tried changing the test case to be neater and now I get failing test case on my local machine as well on repo dropdown.

**Comment by dariusf** [comment]
Nondeterministic in that it only triggers sometimes?

By the way, did you try `comboBox.addEventHandler`? `setOnKeyPressed`, `setOnKeyReleased`, `setOnKeyTyped` should work, failing that?

**Comment by HansNewbie** [comment]
I just added on to current code under `comboBox.addEventFilter(KeyEvent.KEY_RELEASED, event -> {`.

It's kind of negative nondeterministic. Most of the time it fails, but sometimes it passes. I managed to make it work by having a while loop for `sleep` until the value changes. I noticed sometimes it needs 1x `sleep(100)` sometimes it does not, as in the behaviour is weird. The next problem is that the panel names are not updating. After that sleep cycle and all, I keep getting error that no node is found for `"#dummy/dummy_col1_1"` although the default repo is now `"dummy/dummy"`.

**Comment by HansNewbie** [comment]
Just realized it's still `KEY_RELEASED`. Will  change to `KEY_PRESSED`.

**Comment by damithc** [comment]
Do a check for other instances of `KEY_RELEASED` and create issues if they need to be changed.

**Comment by HansNewbie** [comment]
@damithc Noted. I will create issues if I find them, except for the one in listPanel and filterPanel since Rajan is fixing it.
