### PR TITLE
Ctrl + W updates index of selected column

### LINKED ISSUE #489: Ctrl+W sometimes doesn't work
Supposed to close the current panel. Sometimes it works, sometimes it doesn't.

### PR DESCRIPTION
**Pull request by rd1992**
Fixes #489 and #545

### CODE REVIEW

**Comment by dariusf** [comment]
Hmm, should the selection jump to the closest panel instead? For example, when you close tabs in Chrome, selection jumps to the next tab, unless it's the last one in which case it goes to the previous.

**Comment by rd1992** [comment]
@dariusf check it out now. See if this seems more to your liking

File: src/ui/issuecolumn/ColumnControl.java [hunk 1]
```diff
@@ -229,8 +229,19 @@ public void setCurrentlyDraggedColumnIndex(int i) {
 	
 	public void closeCurrentColumn() {
 		if (currentlySelectedColumn.isPresent()) {
-			closeColumn(currentlySelectedColumn.get());
-			currentlySelectedColumn = Optional.empty();
+			int columnIndex = currentlySelectedColumn.get();
+			System.out.println("Going to close column " + columnIndex);
+			closeColumn(columnIndex);
+			if (getChildren() == null || getChildren().size() == 0) {
```
Comment (dariusf) [inline src/ui/issuecolumn/ColumnControl.java]: I don't think `getChildren()` will ever be null. This can be safely omitted, or made into an assertion.

File: src/ui/issuecolumn/ColumnControl.java [hunk 2]
```diff
@@ -229,8 +229,19 @@ public void setCurrentlyDraggedColumnIndex(int i) {
 	
 	public void closeCurrentColumn() {
 		if (currentlySelectedColumn.isPresent()) {
-			closeColumn(currentlySelectedColumn.get());
-			currentlySelectedColumn = Optional.empty();
+			int columnIndex = currentlySelectedColumn.get();
+			System.out.println("Going to close column " + columnIndex);
```
Comment (dariusf) [inline src/ui/issuecolumn/ColumnControl.java]: We should use a logger instead. `System.out.println` has no guarantees of thread safety (and so messages may appear out of order in concurrent scenarios), and won't write to log files.

Comment (rd1992) [inline src/ui/issuecolumn/ColumnControl.java]: ohh wait. i dint intend to put this in !! sorry

**Comment by rd1992** [comment]
ok i checked in some debugging print statements. Removed the redundant code

**Comment by dariusf** [comment]
No worries!
