### PR TITLE
More obvious sign of filter syntax problem #1301

### LINKED ISSUE #1301: More obvious sign of filter syntax problem
Should we make it more obvious when the syntax for the filter is wrong? Something like the bottom half of this:

image

(example from Wireshark)

### PR DESCRIPTION
**Pull request by garbanzos**
Fixes #1301. 

The background colour of the filter text field will change to red when the filter is invalid. Otherwise, the background colour is white. 

The check whether to change the background color happens when 
 - the user presses enter 
 - the filter in the text field changes  

Screenshot
image

### CODE REVIEW

**Comment by acruis** [comment]
Do you have a screenshot for this?

**Comment by damithc** [comment]
@garbanzos In the first comment, did you mean 'red when the filter is **in**valid'? That's how it should be.

File: src/main/java/ui/components/FilterTextField.java [hunk 1]
```diff
@@ -94,6 +97,18 @@ private void setup() {
     }
 
     /**
+     * Set the background of FilterTextField to green if there is no syntax errors.
```
Comment (acruis) [inline src/main/java/ui/components/FilterTextField.java]: `green`?

Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: I suggested not to use green because the only case that needs to be highlighted is errors. If there is no error, we don't have to do anything special.

**Comment by garbanzos** [comment]
@damithc oops yeah i will edit it

File: src/main/java/ui/components/FilterTextField.java [hunk 2]
```diff
@@ -48,13 +48,14 @@ public FilterTextField(String initialText) {
     private void setup() {
         setPrefColumnCount(30);
         validationSupport.registerValidator(this, (c, newValue) -> {
-            boolean wasError = false;
+            boolean isValidFilter = true;
             try {
                 Parser.parse(getText());
             } catch (ParseException e) {
```
Comment (garbanzos) [inline src/main/java/ui/components/FilterTextField.java]: Is there a reason why we are catching ParseException and not catching FilterException (which in includes both ParseException and SemanticExpection)?

**Comment by garbanzos** [comment]
Ready for review.

**Comment by damithc** [comment]
Change the label to reflect the status.

**Comment by ndt93** [comment]
@acruis Can you help review this? Thanks.

File: src/main/java/ui/components/FilterTextField.java [hunk 3]
```diff
@@ -94,6 +95,20 @@ private void setup() {
...
+     * Set the background of FilterTextField to white if there is no syntax errors.
+     * Otherwise, background is set to red
+     *
+     * @param isValidFilter
+     */
+    public void setTextFieldBackground(boolean isValidFilter){
+        if (isValidFilter) {
+            this.setStyle("-fx-control-inner-background: white");
+        } else {
+            this.setStyle("-fx-control-inner-background: #EE8993");
```
Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: May be declare these two magic strings as constants? If you do that, you don't even need this method. It can be `thisSetStyle(isValidFilter ? VALID_FILTER_STYLE : INVALID_FILTER_STYLE)`

File: src/main/java/ui/components/FilterTextField.java [hunk 4]
```diff
@@ -94,6 +95,20 @@ private void setup() {
     }
 
     /**
+     * Set the background of FilterTextField to white if there is no syntax errors.
```
Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: `Sets ...`

File: src/main/java/ui/components/FilterTextField.java (hunk 3 above)
Comment (garbanzos) [inline src/main/java/ui/components/FilterTextField.java]: setTextFieldBackground is also used in FilterPanel to change the background colour of the field text after the user presses enter.

Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: In that case, you can keep the method but still use constants.

File: src/main/java/ui/components/FilterTextField.java [hunk 5]
```diff
@@ -94,6 +100,20 @@ private void setup() {
     }
 
     /**
+     * Sets the background of FilterTextField to white if there is no syntax errors.
```
Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: The color is no longer under the control of this method. Just say the appropriate style will be applied.

File: src/main/java/ui/components/FilterTextField.java [hunk 6]
```diff
@@ -94,6 +100,20 @@ private void setup() {
...
+     * Otherwise, background is set to red
+     *
+     * @param isValidFilter
+     */
+    public void setTextFieldBackground(boolean isValidFilter){
+        if (isValidFilter) {
+            this.setStyle(VALID_FILTER_STYLE);
+        } else {
+            this.setStyle(INVALID_FILTER_STYLE);
+        }
```
Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: The `... ? ... : ...` operator doesn't work here?

File: src/main/java/ui/components/FilterTextField.java (hunk 5 above)
Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: Another thing: this method doesn't even know about syntax errors. Its behavior is controlled by the parameter. Write the comment accordingly. i.e. The comment should reflect ONLY what the method does, not how it is used.

File: src/main/java/ui/components/FilterTextField.java [hunk 7]
```diff
@@ -94,6 +100,16 @@ private void setup() {
     }
 
     /**
+     * Sets the background of FilterTextField to the appropriate color. 
+     * The color set depends on isValidFilter.
```
Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: `color` --> `style`?
Also need to mention how the parameter affects the behavior. i.e. if true, ... otherwise ...

Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: Alternatively (preferred), you can have two methods. `setStyleForValidFilter()` and `setStyleForInvalidFilter()`.
The call site will be more readable that way.

File: src/main/java/ui/components/FilterTextField.java [hunk 8]
```diff
@@ -48,13 +53,15 @@ public FilterTextField(String initialText) {
     private void setup() {
         setPrefColumnCount(30);
         validationSupport.registerValidator(this, (c, newValue) -> {
-            boolean wasError = false;
+            boolean isValidFilter = true;
```
Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: What was the reason for this change?

Comment (garbanzos) [inline src/main/java/ui/components/FilterTextField.java]: Previously, `setTextFieldBackground` required a param `isValidFilter` and was called in `setup`. 

I thought that `setTextFieldBackground (isValidFilter)` was more reader friendly than `setTextFieldBackground(!wasError) so I changed it. 

But since the setting of the style of the background no longer require an argument. I think I will revert the variable back to `wasError`.

Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: Understood. Yup, better to revert back. In the current state it looks like an unnecessary change.

**Comment by acruis** [comment]
I'm not sure if we have any tests to check this behaviour yet in the FilterTextField. I think it's possible to do unit tests for this with Mockito. @damithc does this change warrant more tests to be written?

**Comment by damithc** [comment]
Yes, it would be nice to cover the behavior in tests. But can be done as a separate issue as long as @garbanzos takes that issue immediately after this.

**Comment by garbanzos** [comment]
Created issue #1311.

**Comment by acruis** [comment]
OK, no other comments.

**Comment by dariusf** [comment]
@garbanzos you can [merge](https://github.com/HubTurbo/HubTurbo/blob/master/docs/process.md#merging-a-pull-request) this. Do squash the noisy commits and ensure coverage passes before that.

**Comment by dariusf** [comment]
Not sure why it isn't showing here, but it seems [coverage has increased](https://coveralls.io/builds/5315059). Think this is good to go.
