### PR TITLE
Fix filter field indicating parse errors on incomplete inputs #1360

### LINKED ISSUE #1360: Fix filter field indicating parse errors on incomplete inputs
For example, `id:` is an incomplete but otherwise valid input.

We need this because inputs are validated on the fly, and there are false positives from the parser having too strict a notion of syntactic validity.

### PR DESCRIPTION
**Pull request by dariusf**
Fixes #1360

### CODE REVIEW

**Comment by dariusf** [comment]
@ndt93 could you help to review?

File: src/main/java/filter/Parser.java [hunk 1]
```diff
@@ -17,24 +17,62 @@
...
 
-    private Parser(ArrayList<Token> input) {
+    private final List<Token> input;
+
+    /**
+     * Determines if the parser should fail gracefully if it finds the input
+     * in a incomplete state. See {@link #check}.
+     */
+    private final boolean inCheckMode;
+
```
Comment (ndt93) [inline src/main/java/filter/Parser.java]: Should a boolean flag be named `is...`?

File: src/main/java/ui/components/FilterTextField.java [hunk 2]
```diff
@@ -55,12 +55,19 @@ private void setup() {
         validationSupport.registerValidator(this, (c, newValue) -> {
             boolean wasError = false;
             try {
-                Parser.parse(getText());
-                setStyleForValidFilter();
+                if (!Parser.check(getText())) {
+                    wasError = true;
+                }
```
Comment (ndt93) [inline src/main/java/ui/components/FilterTextField.java]: Naming the variable as `isError` should be better? Also, what is the advantage of having this `check` method instead of catching 2 types of exceptions here?

Comment (dariusf) [inline src/main/java/ui/components/FilterTextField.java]: Changed the name. I thought the interface would be nicer. This way the exception is kept within the parser, and callers have to worry about less (syntax is either correct or not).

File: src/test/java/tests/FilterParserTests.java [hunk 3]
```diff
@@ -52,69 +57,77 @@ public void quotes() {
...
+    @Test(expected = ParseException.class)
+    public void parse_nothingAfterInfixOperator_exceptionThrown() {
+        Parser.parse("a(b) ||");
+    }
 
-        try {
-            Parser.parse("-milestone: label:priority.high");
-            fail("'label:' can't be the input to a qualifier => empty qualifier => parse exception");
-        } catch (ParseException ignored) {}
+    @Test(expected = ParseException.class)
```
Comment (damithc) [inline src/test/java/tests/FilterParserTests.java]: I've seen another way to handle expected exceptions in our tests. Should standardize? http://blog.goyello.com/2015/10/01/different-ways-of-testing-exceptions-in-java-and-junit/

File: src/main/java/filter/Parser.java [hunk 4]
```diff
@@ -17,24 +17,62 @@
...
 public final class Parser {
 
-    private Parser(ArrayList<Token> input) {
+    private final List<Token> input;
+
+    /**
+     * Determines if the parser should fail gracefully if it finds the input
+     * in a incomplete state. See {@link #check}.
+     */
+    private final boolean isInCheckMode;
```
Comment (damithc) [inline src/main/java/filter/Parser.java]: Better name and/or comment? We should explain somewhere what the 'check mode' means.
The comments leans a bit towards 'how it is used' rather than 'what it means'.

File: src/main/java/filter/Parser.java [hunk 5]
```diff
@@ -17,24 +17,62 @@
...
+        }
+
+        try {
+            new Parser(new Lexer(input).lex(), true).parseExpression(0);
+            return true;
+        } catch (IncompleteInputException ignored) {
+            return true;
+        } catch (ParseException ignored) {
+            return false;
+        }
```
Comment (damithc) [inline src/main/java/filter/Parser.java]: Using exceptions to control 'normal' workflow is not exactly right, but may be there is no choice.

**Comment by damithc** [comment]
Waiting for clarifications

File: src/test/java/tests/FilterParserTests.java (hunk 3 above)
Comment (dariusf) [inline src/test/java/tests/FilterParserTests.java]: Okay, I can change it to use ExpectedException. Maybe someone can look into AssertJ in future, as that seems to be more generic and doesn't require fields to be defined.

File: src/main/java/filter/Parser.java (hunk 4 above)
Comment (dariusf) [inline src/main/java/filter/Parser.java]: Maybe `isCheckingSyntax`? 'Check mode' is defined purely by how the flag is used, so maybe we shouldn't try to make it a thing.

File: src/main/java/filter/Parser.java (hunk 5 above)
Comment (dariusf) [inline src/main/java/filter/Parser.java]: Yes, it's used for control flow here. The idea is that if the parser enters certain states, we can return true immediately because we know that the input is incomplete.

The problem is that parseExpression is called recursively from many places, so if we used its return value to indicate this condition, we'd have to change every function signature and add code to propagate it.

This is a bit of an abuse of exceptions but I thought it would be clearer overall.
