### PR TITLE
Hotkey for assignees ('a') doesn't work if the bView is showing commits

### LINKED ISSUE #860: Hotkey for assignees ('a') doesn't work if the bView is showing commits
Currently, it works only if the bView is showing the conversation view. It should load the 'conversation view' and then focus on the assignee property.

### PR DESCRIPTION
**Pull request by rd1992**
Fixes #860

### CODE REVIEW

File: src/main/java/browserview/BrowserComponent.java [hunk 1]
```diff
@@ -486,4 +486,9 @@ public String getCurrentUrl() {
         return driver.getCurrentUrl();
     }
 
+    public void loadTab(String currentUrl) {
```
Comment (damithc) [inline src/main/java/browserview/BrowserComponent.java]: Method name more general than what the method actually does?

**Comment by damithc** [comment]
If ready for review, label accordingly.

File: src/main/java/browserview/BrowserComponent.java [hunk 2]
```diff
@@ -486,4 +486,9 @@ public String getCurrentUrl() {
...
+        if (isCurrentUrlIssue() && (currentUrl.endsWith("/commits") || currentUrl.endsWith("/files"))) {
```
Comment (dariusf) [inline src/main/java/browserview/BrowserComponent.java]: The `endsWith` part can be factored out into `GitHubURL`.

Also I don't think we need to pass the URL as a parameter, given that all this method does is switch to the discussion tab. Conceptually it's not really parameterised by the current URL, and being a `BrowserComponent` method, can already access it.

File: src/main/java/browserview/BrowserComponent.java [hunk 3]
```diff
@@ -486,4 +486,9 @@ public String getCurrentUrl() {
...
+            driver.findElement(By.xpath("//a[@data-container-id='discussion_bucket']")).click();
```
Comment (lejolly) [inline src/main/java/browserview/BrowserComponent.java]: would it be better to just explicitly load the pr page instead of clicking on the tab?

Comment (rd1992) [inline src/main/java/browserview/BrowserComponent.java]: @lejolly no that would involve a page refresh for no reason. We already have visited that page before when user initially clicked on the PR issue in the p view

**Comment by dariusf** [comment]
Looks good. @lejolly?

File: src/main/java/browserview/BrowserComponent.java [hunk 4]
```diff
@@ -486,4 +486,9 @@ public String getCurrentUrl() {
         return driver.getCurrentUrl();
     }
 
+    public void switchToConversationTab() {
+        if (isCurrentUrlIssue() && GitHubURL.isPullRequestLoaded(getCurrentUrl())) {
```
Comment (lejolly) [inline src/main/java/browserview/BrowserComponent.java]: do we need the first check here? since it seems to be called too in all cases this method is called.

File: src/main/java/util/GitHubURL.java [hunk 5]
```diff
@@ -47,4 +47,8 @@ public static String getPathForContributors(String repoId) {
     public static boolean isUrlIssue(String url) {
         return url.matches("https://github.com/([^/]+)/([^/]+)/(issues|pull)/([0-9]+)([/commits,/files]*)");
     }
+    
+    public static boolean isPullRequestLoaded(String url)  {
+        return (url.endsWith("/commits") || url.endsWith("/files"));
+    }
```
Comment (lejolly) [inline src/main/java/util/GitHubURL.java]: cover this in `GitHubURLTest`?

Comment (rd1992) [inline src/main/java/util/GitHubURL.java]: @lejolly have added the tests. can you check and merge?

File: src/main/java/browserview/BrowserComponent.java (hunk 4 above)
Comment (lejolly) [inline src/main/java/browserview/BrowserComponent.java]: is `isCurrentUrlIssue` still needed here?

File: src/main/java/util/GitHubURL.java (hunk 5 above)
Comment (lejolly) [inline src/main/java/util/GitHubURL.java]: looks fine.

**Comment by rd1992** [comment]
@dariusf this was approved my @lejolly. Could you take a look?

**Comment by dariusf** [comment]
I think the only outstanding issue is whether `isCurrentUrlTest` is needed. Otherwise can be merged.

**Comment by rd1992** [comment]
@dariusf you meant isCurrentUrlIssue() i think. I have removed that check

**Comment by lejolly** [comment]
looks good, go ahead and merge it.
