### PR TITLE
F1 key doesn't work when the focus is in a filter box #1167

### LINKED ISSUE #1167: F1 key doesn't work when the focus is in a filter box
F1 should work even when the focus is in a filter box. Even better if pressing F1 while in the filter box goes directly to the 'filters' section of the user docs.

### PR DESCRIPTION
**Pull request by YijinL**
Fixes #1167.

**REVIEW**

**Current status**:
When filter text box is in focus, pressing <kbd>F1</kbd> redirects the browser component to the filter docs page.

**Work done**: 
- ~~`FilterPanel` now passes its `UI` reference to `FilterTextField`~~
- ~~`FilterTextField` now maintains a final field to hold the `UI`reference~~
- ~~`FilterTextField` setup method now includes handling for the `KeyboardShortcuts.SHOW_DOCS` key combination (<kbd>F1</kbd>), which calls UI's browser's`BrowserComponent.showDocs()` method.~~
- ~~The above handling code is copied from a [slice](https://github.com/HubTurbo/HubTurbo/blob/880d65c081505c9e8a547c29d188293a56c5de24/src/main/java/ui/listpanel/ListPanel.java#L171-L173) of `ListPanel.setupKeyboardShorcuts()`~~
- Make F1 link to 'filters' section of docs
- Change implementation: expose help key press callback hook on `FilterTextField` to decouple from rest of app
- All instantiations of `FilterTextField` now register the correct callback for help key press
- Regression testing under `guitests.FilterTextFieldTest`

**Future**:
null

### CODE REVIEW

**Comment by dariusf** [comment]
Some preliminary comments: this couples FilterTextField to the rest of the app, which isn't so good. A better approach would be to expose some kind of callback which lets us hook into its key event.

```java
FilterTextField field = new FilterTextField();
field.setOnHelp(something::showDocs);
// 'Help' being the high-level name for the F1 key press; can be changed
```

I think linking to the filter docs is a good idea also.

**Comment by damithc** [comment]
@YijinL any updates to this PR?

**Comment by YijinL** [comment]
@damithc 
Pressing F1 key when filter text box is in focus now redirects the browser to the filter docs page.
Now working on refactoring the implementation to reduce coupling

**Comment by damithc** [comment]
Noted. Let us know when it is ready for review.

**Comment by YijinL** [comment]
@dariusf implemented following precedent set by FilterTextField.setOnConfirm

File: src/main/java/ui/components/FilterTextField.java [hunk 1]
```diff
@@ -32,7 +34,8 @@
     private static final String INVALID_FILTER_STYLE = "-fx-control-inner-background: #EE8993";
 
     // Callback functions
-    private Runnable cancel = () -> {};
+    private Runnable onCancel = () -> {};
+    private Runnable onHelp = () -> {};
```
Comment (dariusf) [inline src/main/java/ui/components/FilterTextField.java]: This is a good change. Maybe also rename `confirm` while you're at it?

File: src/main/java/ui/components/FilterTextField.java [hunk 2]
```diff
@@ -264,6 +273,15 @@ public FilterTextField setOnConfirm(Function<String, String> confirm) {
     }
 
     /**
+     * Sets the 'onHelp' callback, which will be called when the key combination defined by
+     * KeyboardShortcuts.SHOW_HELP is pressed with this object in focus.
+     */
+    public FilterTextField setOnHelpKeyCombination(Runnable onHelp) {
```
Comment (dariusf) [inline src/main/java/ui/components/FilterTextField.java]: Don't think we need to talk about how the method is used in here. The method name can be a bit shorter also, since the help action is not necessarily triggered by a key combination -- that just happens to be the current implementation.

**Comment by YijinL** [comment]
@dariusf Done as suggested, anything else?

File: src/main/java/ui/components/FilterTextField.java [hunk 3]
```diff
@@ -245,21 +254,26 @@ public void setFilterText(String text) {
...
      * be passed the current contents of the field.
      */
-    public FilterTextField setOnConfirm(Function<String, String> confirm) {
-        this.confirm = confirm;
+    public FilterTextField setOnConfirm(Function<String, String> onConfirm) {
+        this.onConfirm = onConfirm;
+        return this;
+    }
+
+    public FilterTextField setOnHelp(Runnable onHelp) {
```
Comment (dariusf) [inline src/main/java/ui/components/FilterTextField.java]: This can have a similar javadoc comment as the method above.

File: src/test/java/guitests/FilterTextFieldTest.java [hunk 4]
```diff
@@ -121,6 +128,20 @@ public void cancelTest() {
         awaitCondition(() -> toggle.get() % 2 == 1);
     }
 
+    @Test
+    public void helpTest() {
+        UI.events.registerEvent((NavigateToPageEventHandler) e -> url = e.url);
```
Comment (dariusf) [inline src/test/java/guitests/FilterTextFieldTest.java]: Could you use an `AtomicReference<String>` for this instead? So it's kept local to the method.

File: src/test/java/guitests/FilterTextFieldTest.java [hunk 5]
```diff
@@ -121,6 +128,20 @@ public void cancelTest() {
...
+        getFirstPanelField();
+        push(KeyCode.F1);
+        sleep(1000);
```
Comment (dariusf) [inline src/test/java/guitests/FilterTextFieldTest.java]: We can't know that this will take exactly one second. We should wait until the condition is true using `waitAndAssertEquals`.

**Comment by dariusf** [comment]
We should try to get coverage back up. Apart from that the implementation is good. Just a few minor changes suggested.

**Comment by YijinL** [comment]
[ChromeDriverTest](https://github.com/HubTurbo/HubTurbo/blob/8f1ae3aed9dc35c2201e07807d5284b7d9e4f9b1/src/test/java/guitests/ChromeDriverTest.java#L66-L74) uses [this 1000ms duration](https://github.com/HubTurbo/HubTurbo/blob/8f1ae3aed9dc35c2201e07807d5284b7d9e4f9b1/src/test/java/guitests/ChromeDriverTest.java#L21) for event delay, should that one be changed too?

**Comment by dariusf** [comment]
Yes, it should. That's an old test. If you want do it now, you can, otherwise we can make a new issue.

The 5% drop is expected. Could you just check that the previous 0.03% drop is fixed? Should be fine after that.

File: src/main/java/ui/components/FilterTextField.java [hunk 6]
```diff
@@ -245,21 +254,29 @@ public void setFilterText(String text) {
...
      */
-    public FilterTextField setOnConfirm(Function<String, String> confirm) {
-        this.confirm = confirm;
+    public FilterTextField setOnConfirm(Function<String, String> onConfirm) {
+        this.onConfirm = onConfirm;
+        return this;
+    }
+    
+    /**
+     * Sets the 'onHelp' callback, which will be called when F1 is pressed.
```
Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: Perhaps we shouldn't mention when this callback is used? A method should be described independent how it is used.

File: src/test/java/guitests/FilterTextFieldTest.java [hunk 7]
```diff
@@ -121,6 +127,20 @@ public void cancelTest() {
         awaitCondition(() -> toggle.get() % 2 == 1);
     }
 
+    @Test
+    public void helpTest() {
```
Comment (damithc) [inline src/test/java/guitests/FilterTextFieldTest.java]: Follow our new test method naming convention (given in java coding standard)

Comment (YijinL) [inline src/test/java/guitests/FilterTextFieldTest.java]: OK. I followed the local naming conventions from the other tests in this file, so I will change them to verb form as well.
Should I spawn a new issue for the name refactoring, or should I just do it in this PR?

Comment (damithc) [inline src/test/java/guitests/FilterTextFieldTest.java]: Let's write new tests following the new convention. Old ones can be refactored at a later time.

Comment (YijinL) [inline src/test/java/guitests/FilterTextFieldTest.java]: Actually it's a really small change, how about I leave this and you get a free `forFirstTimers` issue? I can help create that issue after this PR gets merged.

File: src/test/java/guitests/FilterTextFieldTest.java [hunk 8]
```diff
@@ -121,6 +127,20 @@ public void cancelTest() {
...
+        AtomicReference<String> url = new AtomicReference<>();
+        UI.events.registerEvent((NavigateToPageEventHandler) e -> url.set(e.url));
+        getFirstPanelField();
+        push(KeyCode.F1);
+        waitAndAssertEquals(GitHubURL.FILTERS_PAGE, url::get);
+    }
+    @Override
```
Comment (damithc) [inline src/test/java/guitests/FilterTextFieldTest.java]: Add a blank line between methods?

File: src/main/java/ui/components/FilterTextField.java (hunk 6 above)
Comment (YijinL) [inline src/main/java/ui/components/FilterTextField.java]: But if we don't mention what event we are hooking the callback on, new developers will have to trace the source to be sure. Or maybe I misunderstood you?

**Comment by YijinL** [comment]
@dariusf Strange all I did was merge `master` into this branch. When coveralls says `coverage increased/decreased to X`, what baseline are they comparing it to?

File: src/main/java/ui/components/FilterTextField.java (hunk 6 above)
Comment (damithc) [inline src/main/java/ui/components/FilterTextField.java]: This method is about binding `Help` to it's implementation, not binding `F1` to help, right?
Another way to look at it is, if we change the Help short cut to `F2` at some point, it should not require a change to this code, and if the code doesn't change, the comment shouldn't change either.
So, is there a better place to explain `F1` is bound to `Help`?

File: src/test/java/guitests/FilterTextFieldTest.java [hunk 9]
```diff
@@ -121,6 +127,21 @@ public void cancelTest() {
         awaitCondition(() -> toggle.get() % 2 == 1);
     }
 
+    @Test
+    public void testHelp() {
```
Comment (damithc) [inline src/test/java/guitests/FilterTextFieldTest.java]: What method or feature are we testing? The method name should be exactly that (i.e. omit `test` part as it is already captured in `@Test`)

File: src/main/java/ui/components/FilterTextField.java (hunk 6 above)
Comment (YijinL) [inline src/main/java/ui/components/FilterTextField.java]: Developers can see the implementation at [`ui.components.KeyboardShortcuts`](https://github.com/HubTurbo/HubTurbo/blob/6e0d10092066fe64fa0415614eba927892fee349/src/main/java/ui/components/KeyboardShortcuts.java#L81-L82).

I see, I will change it to something like:
```java
/**
 * Sets the 'onHelp' callback, which will be called when the user triggers the show_docs keyboard shortcut
 */
```
I suppose line 257: `... called with Esc is pressed ...` 
and line 266: `... called when Enter is pressed ...`
can be left as is since the <kbd>Esc</kbd> and <kbd>Enter</kbd> keybinds are used specially in this class.

File: src/test/java/guitests/FilterTextFieldTest.java (hunk 9 above)
Comment (YijinL) [inline src/test/java/guitests/FilterTextFieldTest.java]: Understood, I will favor the official coding standards over file-local conventions.

**Comment by YijinL** [comment]
Triggering travis rebuild (2 tests failed)

**Comment by YijinL** [comment]
Requesting Travis rebuild, 1 test failed. Seems to be [this](https://travis-ci.org/HubTurbo/HubTurbo/builds/117256446#L3000) one.

**Comment by dariusf** [comment]
I've restarted the build. You can do so yourself by opening/closing the issue, or pushing commits (which you can remove later). If you see specific tests failing frequently, make issues for them.

The baseline is the coverage of the 'merge base' (the common ancestor of this branch and the branch you are merging into).

**Comment by YijinL** [comment]
Noted. Everything seems fine now, thanks!

**Comment by dariusf** [comment]
Do comment when you're done squashing/updating to latest master.

**Comment by YijinL** [comment]
Done.

**Comment by dariusf** [comment]
Thanks!
