### PR TITLE
Show panel stats at the bottom of the panel #1253

### LINKED ISSUE #1253: Show panel stats at the bottom of the panel
We can show number of issues in the panel, broken down by open/closed?
image

### PR DESCRIPTION
**Pull request by yl-coder**
Fixes #1253

### CODE REVIEW

**Comment by damithc** [comment]
Can post a screenshot?

**Comment by yl-coder** [comment]
screen shot 2016-03-14 at 9 33 43 pm

**Comment by damithc** [comment]
@yl-coder comment here when the PR is ready for review.

**Comment by yl-coder** [comment]
Ready for review. Please suggest any changes to be make.

File: src/main/java/ui/listpanel/ListPanel.java [hunk 1]
```diff
@@ -63,10 +68,21 @@ public ListPanel(UI ui, GUIController guiController, PanelControl parentPanelCon
...
         setupListView();
         getChildren().add(listView);
+        getChildren().add(createPanelStats());
+    }
+
+    /**
+     * Create an Graphic element(HBox) containing a label that show the total no of issues in the ListPanel.
+     * @return HBox Instance to be added to the ListPanel.
+     */
+    private HBox createPanelStats() {
```
Comment (damithc) [inline src/main/java/ui/listpanel/ListPanel.java]: May be call it 'PanelFooter' because we might add more than stats to that part of the panel?

File: src/main/java/ui/listpanel/ListPanel.java [hunk 2]
```diff
@@ -63,10 +68,21 @@ public ListPanel(UI ui, GUIController guiController, PanelControl parentPanelCon
...
-
+        totalLabel = new Label("Total : - ");
         listView = new IssueListView();
         setupListView();
         getChildren().add(listView);
+        getChildren().add(createPanelStats());
+    }
+
+    /**
+     * Create an Graphic element(HBox) containing a label that show the total no of issues in the ListPanel.
```
Comment (damithc) [inline src/main/java/ui/listpanel/ListPanel.java]: `Creates`

**Comment by yl-coder** [comment]
I have made the changes.

File: src/main/java/ui/listpanel/ListPanel.java [hunk 3]
```diff
@@ -63,10 +67,21 @@ public ListPanel(UI ui, GUIController guiController, PanelControl parentPanelCon
...
-
+        totalLabel = new Label("Total : - ");
         listView = new IssueListView();
         setupListView();
         getChildren().add(listView);
+        getChildren().add(createPanelFooter());
+    }
+
+    /**
+     * Creates an Graphic element(HBox) containing a label that show the total no of issues in the ListPanel.
```
Comment (damithc) [inline src/main/java/ui/listpanel/ListPanel.java]: an --> a

**Comment by damithc** [comment]
@ndt93 we need a reviewer for this.

**Comment by ndt93** [comment]
Sure I can review this.

File: src/main/java/ui/listpanel/ListPanel.java [hunk 4]
```diff
@@ -63,10 +67,21 @@ public ListPanel(UI ui, GUIController guiController, PanelControl parentPanelCon
         super(ui, guiController, parentPanelControl, panelIndex);
         this.ui = ui;
         this.guiController = guiController;
-
+        totalLabel = new Label("Total : - ");
```
Comment (ndt93) [inline src/main/java/ui/listpanel/ListPanel.java]: This this better be inside of the `createPanelFooter` method? Since it's a subcomponent of the footer.

File: src/main/java/ui/listpanel/ListPanel.java [hunk 5]
```diff
@@ -132,6 +147,9 @@ public final void refreshItems() {
 
         listView.restoreSelection();
         this.setId(guiController.getDefaultRepo() + "_col" + panelIndex);
+        totalLabel.setText(String.format("Total: %d ", issueCount));
+
```
Comment (ndt93) [inline src/main/java/ui/listpanel/ListPanel.java]: For the benefits of generalising with other statistics in the future, this line can be extracted into another method called `updateFooter` or `updateStatistics` for example. (`updateFooter` seems better to me in this case since it's more UI oriented).

**Comment by yl-coder** [comment]
Yes i agree. i have pushed new commits.

**Comment by ndt93** [comment]
@damithc No more comments from me.

@yl-coder I suppose you intended to squash and rename commits' messages later? If not, it would be nice to have a bit more details in the commits' messages and each commit should reflect some meaningful changes. e.g. the refactoring commits after the first commits can be squashed into 1. Also once you are done, please rebase the current master into this branch.

**Comment by yl-coder** [comment]
@ndt93 finished squashing and added more details to the commits' message. Also updated the branch with the latest master branch.

**Comment by ndt93** [comment]
There are some problems with the squash (there are total of 7 commits now). But I suppose this will do for now. You can experiment more with squashing/rebasing in the future.

I will help you to rerun the CI and merge once everything passes. Generally, a PR can't be merged if the CI failed, but we are having some slacks due to some nondeterministic tests recently. You can trigger a rerun by closing and opening the PR again since you don't have permission to rerun yet.

**Comment by yl-coder** [comment]
Thanks! will do next time.

**Comment by ndt93** [comment]
No problem :-)
