### PR TITLE
Experiment with headless testing to stablise UI test #1341

### LINKED ISSUE #1263: Make KeyboardShortcutsConfigTest run reliably on Travis
```
guitests.KeyboardShortcutsConfigTest > invalidKeySpecified FAILED
    org.loadui.testfx.exceptions.NoNodesVisibleException: Matching nodes were found, but none of them were visible. Screenshot saved as /home/travis/build/HubTurbo/HubTurbo/screenshot1455554274261.png.
        at org.loadui.testfx.GuiTest.getVisibleNodes(GuiTest.java:238)
        at org.loadui.testfx.GuiTest.find(GuiTest.java:466)
        at org.loadui.testfx.GuiTest.find(GuiTest.java:306)
        at org.loadui.testfx.GuiTest.pointFor(GuiTest.java:1159)
        at org.loadui.testfx.GuiTest.move(GuiTest.java:849)
        at org.loadui.testfx.GuiTest.click(GuiTest.java:627)
        at guitests.KeyboardShortcutsConfigTest.invalidKeySpecified(KeyboardShortcutsConfigTest.java:67)
```
```
guitests.KeyboardShortcutsConfigTest > invalidKeySpecified FAILED
    java.lang.RuntimeException: java.lang.NullPointerException
        at guitests.UITest.awaitCondition(UITest.java:355)
        at guitests.UITest.awaitCondition(UITest.java:341)
        at guitests.UITest.waitUntilNodeAppears(UITest.java:266)
        at guitests.KeyboardShortcutsConfigTest.invalidKeySpecified(KeyboardShortcutsConfigTest.java:65)
        Caused by:
        java.lang.NullPointerException
            at com.sun.javafx.text.PrismTextLayout.addTextRun(PrismTextLayout.java:755)
            at com.sun.javafx.text.GlyphLayout.breakRuns(GlyphLayout.java:322)
            at com.sun.javafx.text.PrismTextLayout.buildRuns(PrismTextLayout.java:770)
            at com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1021)
            at com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:223)
            at com.sun.javafx.text.PrismTextLayout.getBounds(PrismTextLayout.java:246)
            at javafx.scene.text.Text.getLogicalBounds(Text.java:358)
            at javafx.scene.text.Text.impl_computeGeomBounds(Text.java:1168)
            at javafx.scene.Node.updateGeomBounds(Node.java:3577)
            at javafx.scene.Node.getGeomBounds(Node.java:3530)
            at javafx.scene.Node.getLocalBounds(Node.java:3478)
            at javafx.scene.Node.updateTxBounds(Node.java:3641)
            at javafx.scene.Node.getTransformedBounds(Node.java:3424)
            at javafx.scene.Parent.getChildTransformedBounds(Parent.java:1732)
            at javafx.scene.Parent.recomputeBounds(Parent.java:1524)
            at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1388)
            at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
            at javafx.scene.Node.updateGeomBounds(Node.java:3577)
            at javafx.scene.Node.getGeomBounds(Node.java:3530)
            at javafx.scene.Node.getLocalBounds(Node.java:3478)
            at javafx.scene.Node$MiscProperties$2.computeBounds(Node.java:6472)
            at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9306)
            at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9276)
            at javafx.scene.Node.getBoundsInLocal(Node.java:3156)
            at org.loadui.testfx.utils.FXTestUtils.isNodeWithinSceneBounds(FXTestUtils.java:248)
            at org.loadui.testfx.utils.FXTestUtils.isNodeVisible(FXTestUtils.java:242)
            at org.loadui.testfx.utils.FXTestUtils$6.apply(FXTestUtils.java:233)
            at org.loadui.testfx.utils.FXTestUtils$6.apply(FXTestUtils.java:230)
            at com.google.common.collect.Iterators.indexOf(Iterators.java:778)
            at com.google.common.collect.Iterators.any(Iterators.java:684)
            at com.google.common.collect.Iterables.any(Iterables.java:623)
            at com.google.common.collect.Collections2$FilteredCollection.isEmpty(Collections2.java:186)
            at org.loadui.testfx.GuiTest.getVisibleNodes(GuiTest.java:237)
            at org.loadui.testfx.GuiTest.find(GuiTest.java:466)
            at guitests.UITest.findQuiet(UITest.java:293)
            at guitests.UITest.lambda$waitUntilNodeAppears$8(UITest.java:266)
            at guitests.UITest.awaitCondition(UITest.java:347)
            ... 3 more
```

### LINKED ISSUE #1341: Experiment with headless testing to stablise UI test
## Using monocle
[Monocle](https://wiki.openjdk.java.net/display/OpenJFX/Monocle) allows UI testing that does not depend on native windowing system. Several [sources](http://stackoverflow.com/questions/27403410/headless-testing-with-javafx-and-testfx) have indicated tests that previously failed on C.I were able to pass when run in headless mode. 

## Resources to setup headless testing 
- [Andres Almiray's Weblog](http://www.jroller.com/aalmiray/entry/running_testfx_tests_in_headless)
- [Uwe's blog](https://ustesis.wordpress.com/2014/04/23/headless-ui-testing-with-testfx-and-javafx-8/)
- [Doing headless testing](https://groups.google.com/forum/#!topic/testfx-discuss/u1o7_aznndU)

## Progress
- [Travis log for first completed test in headless mode](https://travis-ci.org/HubTurbo/HubTurbo/builds/117283874)

## Tips for writing test:
- call `waitUntilNodeAppears` on desired node to be found using `find`.
- in headless mode, has trouble typing <kbd>{</kbd> + <kbd>}</kbd>

## Causes of Failing tests:
- `ComparisonFailure due to type method` - PanelRenameTest
- `Drag problem causing Timeout` - PanelTest

### PR DESCRIPTION
**Pull request by jinified**
Fixes #1341 and fixes #1263 

## Tests that failed intermittently on Travis
 - RemovableRepoListAndModelTest
 - MetaUpdateTest

### Push and press methods not registered
 - BoardAutoCreatorTest -> triple pushKeys(CREATE_RIGHT_PANEL) (L50)
 - BoardTest - press(SWITCH_BOARD) not triggered (L146)
 - KeyboardShortcutsTest - press(MAX_WINDOW) (L41) could be full screen issue with Mac
 - PanelFocusTest - pushKeys(JUMP_ISSUE) (L73)
 - PanelRenameTest - pushKeys(CREATE_RIGHT_PANEL) (L152)
 - UIEventTest - press(NEW_ISSUE) (L43)

### Type method does not register properly leading to incomplete input 
 - FilterTest  - type("count:7") (L148)
 - FilterTextFieldTest - type("lo").push(TAB) (L48)
 - IssuePanelTest - type("updated:5") (L81)
 - MetadataUpdateTest - type("updated:24") (L27)
 - UseSessionConfigTest - type("dummy") infected with previous input (L59)
 - ValidLoginTest - type("test") (L32)

### Timeout because of assert and not waiting 
- RemovableRepoListAndModelTest

## Attempted fixes for MacOSX
- use menu traversal menu in place of shortcuts. remember to waitAndAssert for effect of clicking on menu after calling `traverseMenu`
- fire event directly for those without any menu access
- PanelRenameTest - clickOn Panel before clicking on rename button to prevent NPE

## Update
- [x] setting text and firing event seems to work
- [x] Mac has issue with fullscreen support

### CODE REVIEW

**Comment by damithc** [comment]
Keep us posted about the progress. I'm looking forward to the possibility of a more stable test suite.

**Comment by jinified** [comment]
@dariusf  ready for review

**Comment by ndt93** [comment]
@jinified Any updates on this? The coverage seems to drop too much though.

**Comment by jinified** [comment]
No choice. We would need to work on the unstable tests on separate prs.

**Comment by damithc** [comment]
So at this point there is a drop in coverage. Is there a gain in some other area to justify merging this PR?

**Comment by jinified** [comment]
## Pros of merging the PR
- developers can perform headless testing locally which allows to continue working with their machine while running the tests
- the tests that are ported to run in `headless mode` failed less on Travis 
- the individual unstable tests can be handled separately as separate issues since they now also fail locally unlike previous unstable tests that only fail on Travis 
- if we plan to use TestFX4, we should move now before there are more tests being written according to TestFX3 standard

## TODO before merging 
- create issue for unstable tests that failed with similar error or exception 
- confirm that tests work well in both headful and headless mode locally
- create documentation for running headless test

Alternatively, I can continue fixing the tests first before merging. What do you guys think ?

**Comment by damithc** [comment]
I'm ok for merging now. Let us know when ready to review.

File: src/test/java/guitests/UITest.java [hunk 1]
```diff
@@ -49,14 +53,22 @@
...
+public class UITest extends FxRobot {
+    
     private static final Logger logger = LogManager.getLogger(UITest.class.getName());
     protected static final SettableFuture<Stage> STAGE_FUTURE = SettableFuture.create();
     private static final Map<Character, KeyCode> specialCharsMap = getSpecialCharsMap();
-
-    private final Robot robot;
-    private final FXScreenController screenController;
+    
+    // Sets property to run tests headless
```
Comment (damithc) [inline src/test/java/guitests/UITest.java]: properties

File: src/test/java/guitests/UITest.java [hunk 2]
```diff
@@ -70,10 +82,61 @@ public void start(Stage primaryStage) {
...
+        try {
+            if (Files.exists(Paths.get(RepoStore.TEST_DIRECTORY))) {
+                Files.walk(Paths.get(RepoStore.TEST_DIRECTORY), 1)
+                    .filter(Files::isRegularFile)
+                    .filter(p ->
+                        getFileExtension(String.valueOf(p.getFileName())).equalsIgnoreCase("json") ||
+                            getFileExtension(String.valueOf(p.getFileName())).equalsIgnoreCase("json-err")
+                    )
+                    .forEach(p -> new File(p.toAbsolutePath().toString()).delete());
+            }
```
Comment (damithc) [inline src/test/java/guitests/UITest.java]: Can use a guard clause to reduce nesting?

**Comment by ndt93** [comment]
@jinified Should be good if you can fix the unstable tests in the next two weeks, at least those that are currently in the stable tests.

**Comment by jinified** [comment]
Yup. Will try the tests that are previously stable.

**Comment by damithc** [comment]
I'm curious why a commit made 9 hours ago is still 'build in progress'. Don't we get 5 builds in parallel?

**Comment by jinified** [comment]
@ndt93  can help me dogfood this pr. To run in headless mode: 
`CI=true ./gradlew clean test -i`. Just want to confirm it is working

**Comment by ndt93** [comment]
Sure, I will check it out.

**Comment by jinified** [comment]
@ndt93 It seems that both @m133225  and @dariusf  cannot run the tests locally in headless mode.But I can confirm that the headless mode works pretty consistently with Travis now. Perhaps we can create another issue to handle running `headless` on Mac or just run the guitests in `headful` mode for Mac user

**Comment by jinified** [comment]
Update: There are several classes that doesn't seem to run properly on Mac sysem headful or headless.

**Comment by jinified** [comment]
Update: There are several classes that doesn't seem to run properly on Mac system headful or headless. @damithc  @dariusf  @ndt93  Any opinion whether we should merge this PR ? I forsee a lot of issues if we drag this PR any longer because I will need to consistently resolve a lot of conflicts from other merged PR that deals with tests.

**Comment by damithc** [comment]
I'm OK with merging, as long as we iron out the remaining issues over time. @dariusf @ndt93 ?

**Comment by jinified** [comment]
@ndt93 let me fix the failing tests from after merging with master first

**Comment by ndt93** [comment]
Hows the test running on Windows? We should probably mention it somewhere in the docs that Mac users won't be able to run the tests locally so that they can look for alternative systems to run the tests on.

**Comment by jinified** [comment]
No reply from Window user yet.

**Comment by damithc** [comment]
I can try on Windows. What do I need to do?

**Comment by damithc** [comment]
I get this error when I try `gradlew build` on Windows. But the location is correct.
```
ERROR: JAVA_HOME is set to an invalid directory: "C:\Program Files\Java\jdk1.8.0_45"
```

**Comment by jinified** [comment]
Hmm I am not sure about Windows though. Need to run with :
`CI=true gradlew.bat clean test -i`.

**Comment by damithc** [comment]
I managed to run it but I still see GUI during testing. That's not 'headless' right?
The command I used is `gradlew clean build -i -DCI=true`

**Comment by jinified** [comment]
You can either use :
1) `gradlew clean build -i CI=true ` or 
2) `gradlew -Dheadless=true clean build -i` by using the system property 

However running with CI=true will skip the unstable tests. :smile:

**Comment by damithc** [comment]
I tried `gradlew -Dheadless=true clean build` but I still see the GUI during testing. What am I missing?

**Comment by jinified** [comment]
Hmmm. Did u try by declaring the CI=true method ? 
If not the easiest way is to add the line `System.setProperty("headless", "true");` in the [UITest.java](https://github.com/jinified/HubTurbo/blob/1341-headless-testing/src/test/java/guitests/UITest.java#L65-L73)

**Comment by damithc** [comment]
I changed `if (Boolean.getBoolean("headless"))` to `if(true)`. Now tests are running in headless mode. I wonder why it can't get the value set from the command.

**Comment by damithc** [comment]
29 cases failed in headless mode. Similar failure rates with headfull mode too.

**Comment by jinified** [comment]
Using `-Dheadless=true` also doesn't work on `Ubuntu`. But using `CI=true ./gradlew clean test -i` works for both Mac and Ubuntu. If it is not too much trouble, is it possible to upload the test result as zip here or on Slack @damithc

**Comment by dariusf** [comment]
[Here](https://github.com/HubTurbo/HubTurbo/files/195360/headless.zip) are the results of a headless run on Mac.

**Comment by damithc** [comment]
`CI=true ./gradlew clean test -i` is not a valid dos command. Here are the results.
[headless-windows.zip](https://github.com/HubTurbo/HubTurbo/files/195380/headless-windows.zip)

**Comment by jinified** [comment]
Thanks @damithc  and @dariusf . I will analyze those logs but the failures are pretty consistent across these results.

**Comment by ndt93** [comment]
Results for running headless on Mac: 
[log](https://github.com/HubTurbo/HubTurbo/files/197087/headless.zip)

**Comment by jinified** [comment]
@damithc can try to run both headless and headful tests when you are free ? Seems like @dariusf  is able to pass the tests in headful mode

**Comment by damithc** [comment]
Your latest commit has conflict markers in the java code.

**Comment by jinified** [comment]
Really ? There is no error in Eclipse. @dariusf  Is there any error after you update to the latest master ?

**Comment by damithc** [comment]
I'm referring to this branch. Should I be running tests on master branch instead? image

**Comment by jinified** [comment]
@damithc Just pulling this branch will do. But I have no such errors reported. I just updated this branch with latest approved pull request.

**Comment by damithc** [comment]
Yes, the latest version compiles. Here are the results for headfull. 14 failures.
[headfull windows 14 failures.zip](https://github.com/HubTurbo/HubTurbo/files/197570/headfull.windows.14.failures.zip)

**Comment by jinified** [comment]
So I only 1 stable test failed during the headful run. What about result of headless tests ?

**Comment by damithc** [comment]
I've started a headless run before i left office. I'll upload the results tomorrow.

**Comment by ndt93** [comment]
[Results](https://github.com/HubTurbo/HubTurbo/files/197733/headful.zip) for headful run on Mac.

**Comment by damithc** [comment]
Headless on windows, for latest version of this thread, 11 failures. Same result after 2 runs.
[headless windows 11 failures.zip](https://github.com/HubTurbo/HubTurbo/files/198995/headless.windows.11.failures.zip)

**Comment by damithc** [comment]
[windows headless 8 failures.zip](https://github.com/HubTurbo/HubTurbo/files/199095/windows.headless.8.failures.zip)

**Comment by damithc** [comment]
[windows headless 7 failures.zip](https://github.com/HubTurbo/HubTurbo/files/200667/windows.headless.7.failures.zip)

**Comment by jinified** [comment]
Update: Successfully remove all unstable tests and all tests should pass locally except for those using Mac. There are still some tests that fail occasionally on Travis. Remaining todo includes:
- fix broken tests on Mac
- re-run tests on Travis to identify tests that still fail occasionally

**Comment by damithc** [comment]
[windows headless 3 failures.zip](https://github.com/HubTurbo/HubTurbo/files/201176/windows.headless.3.failures.zip)

File: src/test/java/guitests/ContextMenuTests.java [hunk 3]
```diff
@@ -118,29 +115,35 @@ public void contextMenu_selectChangeMilestoneMenu_successful() {
...
         waitUntilNodeAppears("Undo");
-        click("Undo");
+        clickOn("Undo");
         sleep(EVENT_DELAY);
     }
-
+    
+    /**
+     * Click on menu item with target text
+     * @param menu
```
Comment (ndt93) [inline src/test/java/guitests/ContextMenuTests.java]: Should be `Clicks...`

File: src/test/java/guitests/LogoutTest.java [hunk 4]
```diff
@@ -31,11 +32,11 @@ public void logoutFunctionTest() {
         type("dummy").push(KeyCode.TAB);
         type("test").push(KeyCode.TAB);
         type("test");
-        click("Sign in");
+        clickOn("Sign in");
         sleep(2000);
-
-        click("File");
-        click("Logout");
+
```
Comment (ndt93) [inline src/test/java/guitests/LogoutTest.java]: Trailing whitespace. You can set eclipse's save action to remove all trailing white spaces since we might not be able to detect all of those manually.

File: src/test/java/guitests/UIEventTests.java [hunk 5]
```diff
@@ -33,36 +35,36 @@ private static void getEventRepoId(PrimaryRepoChangedEvent e) {
...
-        click("New");
-        click("Label");
+        clickOn("New");
+        clickOn("Label");
         assertEquals(1, eventTestCount);
         resetEventTestCount();
-        press(NEW_LABEL);
-        assertEquals(1, eventTestCount);
+        // press(NEW_LABEL);
+        // assertEquals(1, eventTestCount);
```
Comment (ndt93) [inline src/test/java/guitests/UIEventTests.java]: Should remove all such commented codes.

File: src/test/java/guitests/UITest.java [hunk 6]
```diff
@@ -365,36 +291,30 @@ private void awaitCondition(Callable<Boolean> condition, int timeoutInSeconds) {
             throw new RuntimeException(e);
         }
     }
+    
+    // ====================
+    // Interaction routines
+    // ====================
```
Comment (ndt93) [inline src/test/java/guitests/UITest.java]: These comments here are needed?

File: src/test/java/guitests/UITest.java [hunk 7]
```diff
@@ -560,24 +499,130 @@ public void traverseMenu(String... names) {
...
      */
-    public void selectAll() {
-        pushKeys(new KeyCodeCombination(KeyCode.A, KeyCombination.SHORTCUT_DOWN));
+    public void logout(){
+        clickMenu("File", "Logout");
+    }
+
+    /**
+     * Click on menu item with target text
+     * @param menu
```
Comment (ndt93) [inline src/test/java/guitests/UITest.java]: `Clicks`

File: src/test/java/guitests/LogoutTest.java (hunk 4 above)
Comment (jinified) [inline src/test/java/guitests/LogoutTest.java]: Noted. Thanks for the tips

**Comment by jinified** [comment]
@ndt93 Anymore changes ?

**Comment by jinified** [comment]
@ndt93 Ready for another round of review

File: src/test/java/guitests/UITest.java [hunk 8]
```diff
@@ -133,134 +156,45 @@ private static void clearTestConfig(String directory, String filename) {
...
-    private void press(List<KeyCode> keys) {
-        keys.forEach(this::press);
-        for (int i = keys.size() - 1; i >= 0; i--) {
-            release(keys.get(i));
-        }
-        PlatformEx.waitOnFxThread();
-    }
+    // ================
+    // Waiting routines
+    // ================
```
Comment (ndt93) [inline src/test/java/guitests/UITest.java]: These comments are not needed.

File: src/test/java/guitests/UITest.java [hunk 9]
```diff
@@ -2,62 +2,82 @@
...
+    static {
+        System.setProperty("headless", "true");
+        if (Boolean.getBoolean("headless")) {
+            System.setProperty("java.awt.robot", "true");
+            System.setProperty("testfx.robot", "glass");
+            System.setProperty("testfx.headless", "true");
+            System.setProperty("prism.order", "sw");
+            System.setProperty("prism.text", "t2k");
+        }
+    }
```
Comment (ndt93) [inline src/test/java/guitests/UITest.java]: Can have a brief comments explaining the purpose of these properties?

**Comment by ndt93** [comment]
Some small changes requested.

File: src/test/java/guitests/ContextMenuTests.java [hunk 10]
```diff
@@ -53,9 +50,9 @@ public void contextMenuDisabling_noIssueInListView_contextMenuItemsDisabled() {
         sleep(EVENT_DELAY);
 
         ContextMenu contextMenu = issuePanel.getContextMenu();
-        for (MenuItem menuItem : contextMenu.getItems()) {
-            assertTrue(menuItem.isDisable());
-        }
+        // Problem verifying menu item disable state in headless testing mode
+        // Instead checks for null on first menu item which happens when disabled
+        assertNull(contextMenu.getItems().get(0).getText());
```
Comment (damithc) [inline src/test/java/guitests/ContextMenuTests.java]: You can extract an `isDisabled` method so that the intent become obvious. In that method you can explain why the implementation is 'unusual'

Comment (jinified) [inline src/test/java/guitests/ContextMenuTests.java]: Noted

**Comment by damithc** [comment]
We need to document how to switch between headless and headfull modes. Devs might want to run tests in headfull mode when debugging or writing a new test.
