### PR TITLE
Replace manual menu navigation in tests with clickMenu() #1094

### LINKED ISSUE #1094: Replace manual menu navigation in tests with clickMenu()
Menu tests that use `push(KeyCode.DOWN)` to traverse the menu manually should be replaced with `clickMenu(String... menuNames)` as menu manual traversal will fail in the future if the menu is rearranged.

### PR DESCRIPTION
**Pull request by bsmmoon**
closes #1094 

I replaced `push(KeyCode)` with `clickMenu()`.

There are some cases that needs manual traverse.
1. click() inside clickMenu() cannot handle duplicate menu names (ex. `New` and `Boards / New`)
2. click() will move mouse in straight line, so it may go over another menu and trigger it. It usually happens for diagonal move towards submenu.

These cases are left to use manual traverse.

One more remark..
From line 168, the comment says it deletes `empty` and then `Board 1`, but it actually was deleting `Board 1` and then `empty`. This branch follows the comment and deletes `empty` first and then `Board 1`.

### CODE REVIEW

File: src/test/java/unstable/MenuControlTest.java [hunk 1]
```diff
@@ -73,8 +72,7 @@ public void menuControlTest() {
         assertEquals(false, testPref.getLastOpenBoard().isPresent());
         
         // Testing board save as
-        click("Boards");
-        push(KeyCode.DOWN).push(KeyCode.DOWN).push(KeyCode.ENTER);
+        clickMenu("Boards", "Save");
         ((TextField) find("#boardnameinput")).setText("Board 1");
```
Comment (damithc) [inline src/test/java/unstable/MenuControlTest.java]: Abstract this into a `setTextField` method?

File: src/test/java/unstable/MenuControlTest.java [hunk 2]
```diff
@@ -73,8 +72,7 @@ public void menuControlTest() {
...
         click("OK");
         PlatformEx.waitOnFxThread();
```
Comment (damithc) [inline src/test/java/unstable/MenuControlTest.java]: Abstract this line into a method with a simple name?

**Comment by damithc** [comment]
Let's expand this PR to replace repetitive code snippets in all UI tests into higher-level method calls.

File: src/test/java/unstable/MenuControlTest.java (hunk 1 above)
Comment (dariusf) [inline src/test/java/unstable/MenuControlTest.java]: This is already being done in #1275.

**Comment by dariusf** [comment]
This is a rather old issue, and `clickMenu` has since been subsumed by `traverseMenu`, which was added in #1262. @bsmmoon could you try that instead and see if it works better? Arrow-key traversal is evil.

**Comment by bsmmoon** [comment]
@dariusf Most of the tests in MenuControlTest is removed in the master now. Shall I make similar test cases that it used to have using the new methods?
@damithc OK, I'll work on the rest of the UI tests.

**Comment by dariusf** [comment]
It's been moved to BoardTests (the unstable version). No need to make new ones.

**Comment by bsmmoon** [comment]
@dariusf OK, I think I pretty much changed most of the arrow-key in the guitests.

By the way, I see lots of `assertEquals(expected, actual)` has expected and actual parameters swapped. Shall I correct it or just leave it as it is?

**Comment by damithc** [comment]
Post a new issue regarding swapped expected/actual and note down which places. It can be fixed as a separate PR.

**Comment by bsmmoon** [comment]
@damithc Made. #1281

**Comment by bsmmoon** [comment]
@dariusf I think it is ready for review.

**Comment by dariusf** [comment]
All this seems like it can be just one change. Could you squash? Tell me after that and I'll merge.

**Comment by bsmmoon** [comment]
@dariusf OK, done!

**Comment by dariusf** [comment]
Thanks!
