### PR TITLE
Prompt user to save current board if there are unsaved changes #1199

### LINKED ISSUE #1198: Ctrl+B doesn't work when the open board is deleted
`Ctrl+B` stops switching boards when the currently open board is deleted.

### LINKED ISSUE #1199: Prompt user to save current board if there are unsaved changes

### PR DESCRIPTION
**Pull request by xinan**
Fixes #1198
Fixes #1199 

1. Save the initial panel info when a board is opened. 
2. When switching to another board, check if the current panel info is from the initial one. If so, prompt for save.

### CODE REVIEW

File: src/main/java/ui/ConfirmChangesDialog.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
+package ui;
+
+import javafx.scene.control.Alert;
+import javafx.stage.Stage;
+
+/**
+ * Created by Xinan on 31/1/16.
```
Comment (damithc) [inline src/main/java/ui/ConfirmChangesDialog.java]: We don't usually mention author name in comments.

Comment (xinan) [inline src/main/java/ui/ConfirmChangesDialog.java]: Oh that is auto-generated by IntelliJ. I will remove that.

File: src/main/java/prefs/GlobalConfig.java [hunk 2]
```diff
@@ -30,6 +30,7 @@
     private String lastLoginUsername = "";
     private byte[] lastLoginPassword = new byte[0];
     private Optional<String> lastOpenBoard = Optional.empty();
+    private List<PanelInfo> lastOpenBoardPanelInfo = new ArrayList<>();
```
Comment (damithc) [inline src/main/java/prefs/GlobalConfig.java]: Add a comment to explain the purpose of the variable.

File: src/main/java/ui/MenuControl.java [hunk 3]
```diff
@@ -141,10 +142,30 @@ private void onBoardSaveAs() {
...
+                logger.info("Changes to the current board saved.");
+                // If the user is reloading the current board, and user chose to save current board,
+                if (prefs.getLastOpenBoard().isPresent() && prefs.getLastOpenBoard().get().equals(boardName)) {
+                    // then `newPanelInfo` should be `currentPanelInfo` instead of the `panelInfo` parameter.
+                    newPanelInfo = currentPanelInfo;
+                }
+            } else {
+                logger.info("User abandoned unsaved changes.");
+            }
+        }
```
Comment (damithc) [inline src/main/java/ui/MenuControl.java]: Not enough SLAP here. Can be abstracted out of this method.

**Comment by dariusf** [comment]
How's this going? Need help?

**Comment by dariusf** [comment]
Can this go into the next milestone? It's been open for a while.

File: src/main/java/prefs/PanelInfo.java [hunk 4]
```diff
@@ -23,4 +23,21 @@ public String getPanelFilter() {
...
+    @Override
+    public boolean equals(Object o) {
+        if (this == o) return true;
+        if (o == null || getClass() != o.getClass()) return false;
+
+        PanelInfo panelInfo = (PanelInfo) o;
+
+        if (name != null ? !name.equals(panelInfo.name) : panelInfo.name != null) return false;
+        return filter != null ? filter.equals(panelInfo.filter) : panelInfo.filter == null;
+    }
```
Comment (ndt93) [inline src/main/java/prefs/PanelInfo.java]: The 2 lines above are not every readable, especially using the result of a `?` operator in the conditional expression for the `if` statement. You can use 2 `||` operators instead. But it's better to have multiple if clauses or expressions to reflect clearly the equality criteria.

File: src/main/java/ui/ConfirmChangesDialog.java [hunk 5]
```diff
@@ -0,0 +1,19 @@
+package ui;
+
+import javafx.scene.control.Alert;
+import javafx.stage.Stage;
+
+public class ConfirmChangesDialog extends Alert {
```
Comment (ndt93) [inline src/main/java/ui/ConfirmChangesDialog.java]: New class needs a header comment.

File: src/main/java/ui/MenuControl.java [hunk 6]
```diff
@@ -161,9 +140,41 @@ private void onBoardSaveAs() {
             String boardName = response.get().trim();
             prefs.addBoard(boardName, panelList);
             prefs.setLastOpenBoard(boardName);
+            prefs.setLastOpenBoardPanelInfo(panelList);
             ui.triggerEvent(new BoardSavedEvent());
             logger.info("New board " + boardName + " saved");
             ui.updateTitle();
+            return true;
+        } else {
+            return false;
```
Comment (ndt93) [inline src/main/java/ui/MenuControl.java]: You can put the guard clause first to reduce nesting i.e.
```java
if (!response.isPresent()) {
    return false;
}
// Successful flow
```

File: src/main/java/ui/MenuControl.java [hunk 7]
```diff
@@ -161,9 +140,41 @@ private void onBoardSaveAs() {
...
+        }
+    }
+
+    /**
+     * Prompt use for whether to save the current board panel info or not
+     * when user is closing current board (i.e. switching to another board)
```
Comment (ndt93) [inline src/main/java/ui/MenuControl.java]: According to our convention, should start with `Prompts` since it's a abbreviation for `This method prompts...`

File: src/main/java/ui/MenuControl.java [hunk 8]
```diff
@@ -161,9 +140,41 @@ private void onBoardSaveAs() {
...
+                onBoardSave();
+                logger.info("Changes to the current board saved.");
+                return true;
+            } else {
+                logger.info("User abandoned unsaved changes.");
+                return false;
+            }
+        } else {
+            // No changes to current board, no need to save.
+            return false;
```
Comment (ndt93) [inline src/main/java/ui/MenuControl.java]: Same here, can put guard clauses first to reduce nesting. Also if the `if` branch ends with a `return` then we don't need an `else` clause.

File: src/main/java/ui/MenuControl.java [hunk 9]
```diff
@@ -161,22 +140,65 @@ private void onBoardSaveAs() {
...
             logger.info("New board " + boardName + " saved");
             ui.updateTitle();
+            return true;
+        } else {
+            return false;
         }
     }
 
     /**
+     * This method prompts the user for whether to save the current board panel info or not
```
Comment (damithc) [inline src/main/java/ui/MenuControl.java]: Remove `This method`

**Comment by damithc** [comment]
@ndt93 any more comments on this PR?

File: src/main/java/prefs/PanelInfo.java [hunk 10]
```diff
@@ -23,4 +23,36 @@ public String getPanelFilter() {
...
+            return false;
+        }
+
+        if (filter != null) {
+            if (!filter.equals(panelInfo.filter)) {
+                return false;
+            }
+        } else if (panelInfo.filter != null) {
+            return false;
+        }
```
Comment (ndt93) [inline src/main/java/prefs/PanelInfo.java]: Sorry I didn't make this very clear last time. Is something like this better?
```java
if (name != null && !name.equals(panelInfo.name)) {
    return false;
}
if (panelInfo.name != null) {
    return false;
}

if (filter != null && !filter.equals(panelInfo.filter)) {
    return false;
}
if (panelInfo.filter != null) {
    return false;
}
```
Better still, you can use variables to make things more readable e.g.
```java
boolean isPanelNamesDifferent = name != null && !name.equals(panelInfo.name);
if (isPanelNamesDifferent) {
...
}
...
```

**Comment by ndt93** [comment]
Added a comment about nesting `if`s, and I think the comment about putting guard clause first is still not resolved yet.

File: src/main/java/prefs/PanelInfo.java (hunk 10 above)
Comment (xinan) [inline src/main/java/prefs/PanelInfo.java]: How about this
```
return Objects.equals(name, panelInfo.name) && Objects.equals(filter, panelInfo.filter);
```

File: src/main/java/ui/MenuControl.java [hunk 11]
```diff
@@ -95,35 +95,14 @@ private Menu createFileMenu() {
...
-    /**
-     * Returns a boolean indicating whether we can proceed with
-     * the new board creation. If there are no panels open, it
-     * returns true; else a dialog is shown for the user to confirm.
-     */
-    private boolean isNewBoardCreationDialogConfirmed() {
-        List<PanelInfo> panelList = panels.getCurrentPanelInfos();
-        if (panelList.isEmpty()) {
-            return true;
+        boolean aborted = !onBoardSaveAs();
```
Comment (damithc) [inline src/main/java/ui/MenuControl.java]: boolean variable is not named like a boolean

File: src/main/java/prefs/PanelInfo.java (hunk 10 above)
Comment (ndt93) [inline src/main/java/prefs/PanelInfo.java]: That's nice :+1: , unless you want it to return false when both are `null`s

Comment (xinan) [inline src/main/java/prefs/PanelInfo.java]: I think we don't need to worry about the case when both are `null`s.

File: src/main/java/prefs/GlobalConfig.java [hunk 12]
```diff
@@ -30,6 +30,12 @@
     private String lastLoginUsername = "";
     private byte[] lastLoginPassword = new byte[0];
     private Optional<String> lastOpenBoard = Optional.empty();
+
+    // Save the panel info of the last opened board, so that we can determine
+    // whether the current opened board is dirty by comparing the saved
+    // panel info and the current panel info.
```
Comment (damithc) [inline src/main/java/prefs/GlobalConfig.java]: Just explain what the variable holds

Comment (damithc) [inline src/main/java/prefs/GlobalConfig.java]: And use javadoc comment format

File: src/main/java/ui/MenuControl.java [hunk 13]
```diff
@@ -157,14 +136,46 @@ private void onBoardSaveAs() {
...
+     * @return true if user choose to save, false if user choose to discard
+     */
+    private boolean promptToSaveCurrentBoard() {
+        List<PanelInfo> currentPanelInfo = panels.getCurrentPanelInfos();
+        List<PanelInfo> lastOpenBoardPanelInfo = prefs.getLastOpenBoardPanelInfo();
+
+        if (currentPanelInfo.equals(lastOpenBoardPanelInfo)) {
+            // No changes to current board, no need to save.
+            return false;
+        }
```
Comment (damithc) [inline src/main/java/ui/MenuControl.java]: This makes the implementation not-as-advertised. If the method is for 'prompting the user', the decision whether to prompt should be taken outside the method. The code should read like
```
if(hasBoardChanged(...)) promptToSaveCurrentBoard()
```

File: src/main/java/ui/MenuControl.java [hunk 14]
```diff
@@ -173,10 +184,21 @@ private void onBoardSaveAs() {
     private void onBoardOpen(String boardName, List<PanelInfo> panelInfo) {
         logger.info("Menu: Boards > Open > " + boardName);
 
+        List<PanelInfo> currentPanelInfo = panels.getCurrentPanelInfos();
+        List<PanelInfo> newPanelInfo = panelInfo;
+
+        boolean isCurrentBoardSaved = promptToSaveCurrentBoard();
+
+        if (isCurrentBoardSaved && prefs.getLastOpenBoard().isPresent()
+                && prefs.getLastOpenBoard().get().equals(boardName)) {
```
Comment (damithc) [inline src/main/java/ui/MenuControl.java]: Use an explanatory variable to clarify what this 3-part condition means?

**Comment by damithc** [comment]
Some cosmetic changes requested. Let us know when ready for review again.

**Comment by xinan** [comment]
@damithc Hey Prof! It is ready for review again!

File: src/main/java/ui/MenuControl.java [hunk 15]
```diff
@@ -157,14 +150,40 @@ private void onBoardSaveAs() {
...
+        Optional<ButtonType> response = dlg.showAndWait();
+        prefs.setLastOpenBoardPanelInfo(currentPanelInfo);
+        if (response.get() != ButtonType.OK) {
+            logger.info("User abandoned unsaved changes.");
+            return false;
         }
+
+        onBoardSave();
+        logger.info("Changes to the current board saved.");
+        return true;
```
Comment (damithc) [inline src/main/java/ui/MenuControl.java]: Is the return value used?

Comment (damithc) [inline src/main/java/ui/MenuControl.java]: This method is doing more than advertised.

File: src/main/java/ui/components/KeyboardShortcuts.java [hunk 16]
```diff
@@ -57,6 +57,8 @@
 
     // non-customizable keyboard shortcuts
     // ui.listpanel.ListPanel
+    public static final KeyCodeCombination ENTER =
+            new KeyCodeCombination(KeyCode.ENTER);
```
Comment (damithc) [inline src/main/java/ui/components/KeyboardShortcuts.java]: Is this used somewhere?

**Comment by damithc** [comment]
Some changes requested.

**Comment by xinan** [comment]
Unfortunately, #1171 and #1217 are both quite buggy, I have to fix the bugs in them because making them compatible with this PR.

**Comment by damithc** [comment]
Go ahead. Preferably, as separate PRs.

**Comment by xinan** [comment]
@damithc I opened #1460 and #1461 and will fix them soon. I would appreciate if we don't merge anything new that is related to boards or its menus until I fix them.

**Comment by damithc** [comment]
OK @xinan. If there are any open PRs that belong to that category, add a comment in those PRs.

**Comment by damithc** [comment]
Let us know when this is ready to review again.

**Comment by xinan** [comment]
Sure. Need to wait for #1485

**Comment by ndt93** [comment]
@xinan Can help fix the conflicts with master for this?

**Comment by xinan** [comment]
Ping 😊
