### PR TITLE
Fix failures in PanelsTest #1124

### LINKED ISSUE #1124: Fix failures in PanelsTest
This fails offline but passes on Travis. Blocking #1123.

### PR DESCRIPTION
**Pull request by dariusf**
Fixes #1124.

This makes the panel-dragging test reliable. @HyungJon you might also want to take a look.

### CODE REVIEW

**Comment by HyungJon** [comment]
Yes, I think this is fine now, since both functions are tested.
Do you think there's a need for more tests regarding this function e.g. not just swapping with direct left/right but dragging over another panel (3 panels, drag leftmost to far right)?

File: src/test/java/guitests/PanelsTest.java [hunk 1]
```diff
@@ -1,80 +1,63 @@
...
         click(name1);
-        assertTrue(eventTriggered.value);
+        TestUtils.awaitCondition(eventTriggered::get);
 
-        // Drag
-        // TODO find a way to actually reorder the panels, and make it compatible with swap key command
+        // Reorder panels by dragging, and wait for them to swap position
+        final AbstractPanel firstPanel = panels.getPanel(0);
+        Node from = ((FilterPanel) panels.getPanel(1)).getCloseButton();
+        Node to = ((FilterPanel) panels.getPanel(0)).getFilterTextField();
```
Comment (HansNewbie) [inline src/test/java/guitests/PanelsTest.java]: Why don't we use close button as well here? Might be confusing in the future. If there is a reason why we use filter text field instead of close button, maybe put a comment about it?

**Comment by HansNewbie** [comment]
I think what @HyungJon suggested sounds good. Since we test dragging to the left, maybe for this test drag to the right?

File: src/test/java/guitests/PanelsTest.java (hunk 1 above)
Comment (dariusf) [inline src/test/java/guitests/PanelsTest.java]: With the close button as a target, the swap doesn't actually trigger. It's due to the way the node hierarchy is set up.

I've pulled out the means of getting the node into a method, so we can change that if the node hierarchy changes.

**Comment by dariusf** [comment]
Okay, I've added a third panel, and tests for dragging left/right as well as swapping left/right with hotkeys.

File: src/test/java/guitests/PanelsTest.java [hunk 2]
```diff
@@ -82,8 +50,60 @@ public void panelsTest() {
         type("dummy2/dummy2");
         push(KeyCode.ENTER);
         pushKeys(CREATE_RIGHT_PANEL);
-        PlatformEx.waitOnFxThread();
-        // Actually a check. If #dummy2/dummy2_col1 did not exist, this would throw an exception.
-        click("#dummy2/dummy2_col1");
+
+        waitUntilNodeAppears(panel1);
```
Comment (HansNewbie) [inline src/test/java/guitests/PanelsTest.java]: Is this the same as the original? To me it seems that originally we want to assert that a panel can be created after dragging other panels. But in this wait, we just check if the original panel is still present after creating a new panel.

Comment (dariusf) [inline src/test/java/guitests/PanelsTest.java]: Good catch, it's different.

**Comment by HansNewbie** [comment]
Good to go.
