### PR TITLE
Model is deleted when repo letter casing is wrong #1060

### LINKED ISSUE #1060: Model is deleted when repo letter casing is wrong
e.g. default repo is `TEAMMATES/repo` and filter is `(repo:TEAMMATES/repo || repo:hubturbo/hubturbo)`. Everytime something is added to the filter, the model of HubTurbo will be deleted and reloaded.

Will cause same issue with #1056, except that the only blank issues would be HubTurbo's issue and TEAMMATES's issue would show up just fine.

### PR DESCRIPTION
**Pull request by HansNewbie**
Fixes #1060

### CODE REVIEW

**Comment by HansNewbie** [comment]
This PR corrects 2 things:
- Model deletion should be case insensitive (as per issue).
- `Repos` > `Remove` listing is now also case insensitive 
  - this is a bug whereby the list might have double entries (with one not being marked as being `in use`) if using `repo` qualifier with the content being in wrong letter casing.

Wrote tests to ensure case sensitive problem does not happen again.

**Comment by HansNewbie** [comment]
@ndt93 can help me review this PR?

Basically the two things I am tackling is:
Given that there is a repo in the system (say `HubTurbo/HubTurbo`) but it is not default repo, the following cases should not happen:
- When using `(repo:dummy/dummy || repo:hubturbo/hubturbo)` - notice the different letter casing - the model of HubTurbo/HubTurbo should not be loaded and deleted after every filter changing. This happened because the model loaded will follow the original `repoId`, which is with big `H` and `T`, but the one passed to remove model method is with small `h` and `t`.
- Different repo letter casing will cause them to be listed in `Repos > Remove` separately. Say for the same given case, my filter is `repo:hubturbo/hubturbo` - in different letter casing. This will cause `Repos > Remove` to list `HubTurbo/HubTurbo` as removable (i.e. not in use) while `hubturbo/hubturbo` as non-removable. Hence, user might delete the JSON of `HubTurbo/HubTurbo` even though it's in use.

I am running the tests locally now, will notify again if it all passes.

**Comment by HansNewbie** [comment]
@ndt93 it passed local tests.

File: src/main/java/backend/Logic.java [hunk 1]
```diff
@@ -188,9 +188,9 @@ public String getDefaultRepo() {
     }
 
     public void removeUnusedModels(Set<String> reposInUse) {
-        models.toModels().stream().map(Model::getRepoId).
-                filter(repoId -> !reposInUse.contains(repoId)).
-                forEach(repoIdNotInUse -> models.removeRepoModelById(repoIdNotInUse));
+        models.toModels().stream().map(Model::getRepoId)
+                .filter(repoId -> !reposInUse.contains(repoId.toLowerCase()))
+                .forEach(repoIdNotInUse -> models.removeRepoModelById(repoIdNotInUse));
```
Comment (ndt93) [inline src/main/java/backend/Logic.java]: Although we take care of `toLowerCase` inside, it could be helpful to add a method's comment recommending at `reposInUse` should be normalized as a precondition.

File: src/main/java/ui/UI.java [hunk 2]
```diff
@@ -350,14 +351,18 @@ private Parent createRootNode() {
     public Set<String> getCurrentlyUsedRepos() {
         Set<String> currentlyUsedRepos = new HashSet<>();
         String defaultRepo = logic.getDefaultRepo();
-        currentlyUsedRepos.add(defaultRepo);
         currentlyUsedRepos.addAll(panels.getRepositoriesReferencedOnAllPanels());
+        if (!currentlyUsedRepos.stream().map(String::toLowerCase)
+                .collect(Collectors.toSet()).contains(defaultRepo.toLowerCase())) {
+            currentlyUsedRepos.add(defaultRepo);
+        }
```
Comment (ndt93) [inline src/main/java/ui/UI.java]: `getCurrentlyUsedRepos` could have a method's comment mentioning a post-condition that all repo ids are normalized (spaces removed/lowercase etc.). Maybe we should have some sorts of a separate `normalize` method in `Utility` that does all the repo clean up. But this all these won't be necessary anymore if we solve #1078

File: src/main/java/ui/MenuControl.java [hunk 3]
```diff
@@ -336,9 +334,11 @@ private MenuItem createRefreshMenuItem() {
...
         remove.getItems().clear();
 
-        Set<String> currentlyUsedRepos = ui.getCurrentlyUsedRepos();
-        Set<String> removableRepos = ui.logic.getStoredRepos();
-        removableRepos.removeAll(currentlyUsedRepos);
+        Set<String> currentlyUsedRepos = ui.getCurrentlyUsedRepos()
+                .stream().map(String::toLowerCase).collect(Collectors.toSet());
+        Set<String> removableRepos = ui.logic.getStoredRepos()
+                .stream().filter(repoId -> !currentlyUsedRepos.contains(repoId.toLowerCase()))
+                .collect(Collectors.toSet());
```
Comment (ndt93) [inline src/main/java/ui/MenuControl.java]: If `getCurrentlyUsedRepos` already provides some guarantees, are all the extra `toLowerCase` necessary?

File: src/main/java/ui/UI.java (hunk 2 above)
Comment (HansNewbie) [inline src/main/java/ui/UI.java]: Yep, will make normalize in Utility and add comment on it that should be removed once #1078 is done.

File: src/main/java/ui/MenuControl.java (hunk 3 above)
Comment (HansNewbie) [inline src/main/java/ui/MenuControl.java]: So `getCurrentlyUsedRepos` does not normalize the names to lower cases as we would like to show it as what the user has input. Just a few lines below this we will call non-normalize `getCurrentlyUsedRepos`. `toLowerCase` for `repoId` is called (instead of mapped) because we would like to use the original `repoId` casing instead of the normalized one as per the reason mentioned.

File: src/main/java/backend/Logic.java (hunk 1 above)
Comment (HansNewbie) [inline src/main/java/backend/Logic.java]: Added comment.

**Comment by ndt93** [comment]
All right, this should be good to merge then.
