### PR TITLE
Make sure most qualifiers throw Exception for invalid input #1174

### LINKED ISSUE #1174: Unexpected inputs should trigger parse exceptions instead of failing silently
All qualifiers should be changed to throw exceptions on unexpected conditions instead of returning `EMPTY`. `EMPTY` is what is defaulted to *upon* an exception, and should not be used directly as much as possible.

### PR DESCRIPTION
**Pull request by jinified**
Fixes #1174 

- [X] create FilterException and subclassed by ParseException and SemanticException 
- [X] change applyStringFilter to catch `FilterException`
- [x] change id, state, has, no, in, type, is, created, updated, repo,

### CODE REVIEW

File: src/main/java/filter/ParseException.java [hunk 1]
```diff
@@ -1,8 +1,8 @@
 package filter;
 
 @SuppressWarnings("serial")
-public class ParseException extends RuntimeException {
+public class ParseException extends FilterException {
       public ParseException(String message) {
-         super(message);
+         super("Parse error in filter: " + message);
```
Comment (damithc) [inline src/main/java/filter/ParseException.java]: Is this going to be shown to the user? In that case, you may want to say 'Error in filter'.

File: src/main/java/filter/SemanticException.java [hunk 2]
```diff
@@ -0,0 +1,9 @@
+package filter;
+
+@SuppressWarnings("serial")
+public class SemanticException extends FilterException {
+    public SemanticException(String message) {
+        super("Semantic error in filter: " + message);
```
Comment (damithc) [inline src/main/java/filter/SemanticException.java]: If this is going to be shown to the user, use a more user friendly phrase.

File: src/main/java/undo/UndoController.java [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+    }
+
+    private Label createInfoOcticon() {
+        Label label = new Label(OCTICON_INFO);
+        label.setPadding(new Insets(0, 0, 5, 0));
+        label.getStyleClass().addAll("octicon");
+        return label;
+    }
+
+}
```
Comment (damithc) [inline src/main/java/undo/UndoController.java]: Is this part of this PR, or came from another PR? If the latter, need to clean up the PR first.

File: src/main/java/filter/ParseException.java (hunk 1 above)
Comment (jinified) [inline src/main/java/filter/ParseException.java]: I was just using the format of the previous ParseException.

File: src/main/java/undo/UndoController.java (hunk 3 above)
Comment (jinified) [inline src/main/java/undo/UndoController.java]: It came from another PR, I will cleanup the PR before I ask for a review

File: src/main/java/filter/SemanticException.java (hunk 2 above)
Comment (jinified) [inline src/main/java/filter/SemanticException.java]: I am already planning to change the message and add suggestion of supported inputs

File: src/main/java/filter/SemanticException.java [hunk 4]
```diff
@@ -0,0 +1,11 @@
+package filter;
+
+import filter.expression.QualifierType;
+
+@SuppressWarnings("serial")
+public class SemanticException extends FilterException {
+    public SemanticException(QualifierType type) {
+        super(String.format("Invalid input in filter for type \"%s\"", type));
```
Comment (dariusf) [inline src/main/java/filter/SemanticException.java]: We don't have a lot of room in the status bar, so we might want to make the preamble shorter.

Also, this constructor could take another parameter for the details of the error. We should explain why the input causes a problem.

File: src/test/java/tests/FilterEvalTests.java [hunk 5]
```diff
@@ -9,19 +9,28 @@
...
+import filter.expression.QualifierType;
 import prefs.Preferences;
 
 public class FilterEvalTests {
 
+    @Rule
+    public ExpectedException thrown = ExpectedException.none();
+
     private final IModel empty;
+    private static final String SEMANTIC_ERROR_MSG = "Invalid input in filter for"
```
Comment (dariusf) [inline src/test/java/tests/FilterEvalTests.java]: Could this field be in one of the exception classes? Otherwise we have to duplicate it here.

File: src/main/java/filter/SemanticException.java (hunk 4 above)
Comment (jinified) [inline src/main/java/filter/SemanticException.java]: Ok will work making the preamble shorter. The explanation can be universal like the input is not supported because a more specific explanation like what type of inputs are only supported would be too long to fit in the status bar also

File: src/test/java/tests/FilterEvalTests.java (hunk 5 above)
Comment (jinified) [inline src/test/java/tests/FilterEvalTests.java]: I can put this in the SemanticException class

**Comment by jinified** [comment]
What do @dariusf  think about these error message ? 

error_msg

**Comment by dariusf** [comment]
Maybe we can drop the preamble entirely, and make the message as friendly as possible. For example,

```
"id" expects a number or a number range
"is" expects "open", "closed", "pr", "issue", or "read"
```
(Also the distinction between a data type and a string literal is made clearer.)

We can use the extra room to show the panel name instead of the number. Might need additional truncation on our end.

@damithc how do you find this?

By the way, we should find a way to integrate this new type of error into the [existing display](https://github.com/jinified/HubTurbo/blob/1174-unexpected-input-trigger-exception/src/main/java/ui/components/FilterTextField.java#L54) (which right now is quite coupled and only picks up parse errors), but that can be a separate issue.

**Comment by damithc** [comment]
I agree.

**Comment by jinified** [comment]
ready for review @dariusf

File: src/main/java/filter/expression/QualifierType.java [hunk 6]
```diff
@@ -31,6 +32,27 @@
         return Collections.unmodifiableMap(aliases);
     }
 
+    // Ignore Qualifiers that expects a string where any user input would be valid
+    private static Map<QualifierType, String> initialiseValidInputs() {
+        Map<QualifierType, String> validInputs = new HashMap<>();
+        validInputs.put(ID, "a number or a number range");
+        validInputs.put(UPDATED, "a number or  a number range");
```
Comment (dariusf) [inline src/main/java/filter/expression/QualifierType.java]: Extra space here. :stuck_out_tongue:

File: src/main/java/filter/expression/QualifierType.java [hunk 7]
```diff
@@ -31,6 +32,27 @@
...
+        validInputs.put(STATE, "\"open\" or \"closed\"");
+        validInputs.put(HAS, "\"label\", \"milestone\", or \"assignee\"");
+        validInputs.put(NO, "\"label\", \"milestone\", or \"assignee\"");
+        validInputs.put(IN, "\"title\" or \"body\"");
+        validInputs.put(TYPE, "\"issue\" or \"pr\"");
+        validInputs.put(CREATED, "a date or a date range");
+        validInputs.put(REPO, "repo id");
+        
+        //Show only most common inputs to safe space
```
Comment (dariusf) [inline src/main/java/filter/expression/QualifierType.java]: Typo here ("save space"). Also, aren't these all the keywords? Do you mean the frequently-used ones are ordered first?

File: src/main/java/filter/expression/QualifierType.java [hunk 8]
```diff
@@ -31,6 +32,27 @@
...
+        validInputs.put(IS, "\"open\", \"closed\", \"pr\", \"issue\", \"merged\","
+                + " \"read\", \"unread\", or \"unmerged\"");
+        validInputs.put(SORT, "\"comments\", \"repo\", \"updated\", \"id\", "
+                + " \"assignee\", \"label\", \"state\", or \"milestone\"");
```
Comment (dariusf) [inline src/main/java/filter/expression/QualifierType.java]: `sort` doesn't expect the string "label", but a label name.

File: src/main/java/ui/issuepanel/FilterPanel.java [hunk 9]
```diff
@@ -174,11 +173,11 @@ private void applyStringFilter(String filterString) {
             } else {
                 this.applyFilterExpression(Qualifier.EMPTY);
             }
-        } catch (ParseException ex) {
+        } catch (FilterException ex) {
             this.applyFilterExpression(Qualifier.EMPTY);
             // Overrides message in status bar
             UI.status.displayMessage("Panel " + (panelIndex + 1)
-                + ": Parse error in filter: " + ex.getMessage());
+                + ": " + ex.getMessage());
```
Comment (dariusf) [inline src/main/java/ui/issuepanel/FilterPanel.java]: This is a bit tangential, but maybe we could add the panel name here, defaulting to the index only if it's unnamed?

Comment (jinified) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Sure. I was afraid to edit that since it is not part of the issue. I will edit that

File: src/main/java/filter/expression/QualifierType.java (hunk 8 above)
Comment (jinified) [inline src/main/java/filter/expression/QualifierType.java]: Miss out on that. Thanks.

File: src/main/java/filter/expression/QualifierType.java (hunk 7 above)
Comment (jinified) [inline src/main/java/filter/expression/QualifierType.java]: Yup

Comment (dariusf) [inline src/main/java/filter/expression/QualifierType.java]: Okay, we should update the comment.

File: src/test/java/tests/FilterEvalTests.java [hunk 10]
```diff
@@ -37,6 +44,17 @@ public boolean matches(String filterExpr, TurboIssue issue) {
         return Qualifier.process(empty, Parser.parse(filterExpr), issue);
     }
 
+    /**
+     * Helper method for testing SemanticException thrown by different qualifiers
+     */
+    public void expectSemanticException(QualifierType type, String invalidInput) {
```
Comment (damithc) [inline src/test/java/tests/FilterEvalTests.java]: `verifySemanticExceptionThrown`?

Comment (jinified) [inline src/test/java/tests/FilterEvalTests.java]: Yes. That actually seems like a better method name

**Comment by jinified** [comment]
ready for review @dariusf

File: src/main/java/filter/SemanticException.java [hunk 11]
```diff
@@ -0,0 +1,14 @@
+package filter;
+
+import filter.expression.QualifierType;
+
+@SuppressWarnings("serial")
+public class SemanticException extends FilterException {
+    
+    public static final String ERR_MSG = "\"%s\" expects %s";
```
Comment (dariusf) [inline src/main/java/filter/SemanticException.java]: I know this is more or less unambiguous in context, but we should try not to abbreviate names, just as a matter of style.

File: src/main/java/filter/expression/QualifierType.java [hunk 12]
```diff
@@ -31,6 +32,26 @@
         return Collections.unmodifiableMap(aliases);
     }
 
+    // Set valid inputs for each keyword except those that takes in any string
```
Comment (dariusf) [inline src/main/java/filter/expression/QualifierType.java]: This can be a javadoc comment.

File: src/main/java/filter/expression/QualifierType.java [hunk 13]
```diff
@@ -93,4 +114,11 @@ private static boolean isSpecialQualifier(String input) {
     public String toString() {
         return name().toLowerCase();
     }
+    
+    public String getValidInputs() {
```
Comment (dariusf) [inline src/main/java/filter/expression/QualifierType.java]: We should add a javadoc comment to this.

File: src/main/java/ui/issuepanel/FilterPanel.java [hunk 14]
```diff
@@ -174,14 +173,21 @@ private void applyStringFilter(String filterString) {
...
             // Overrides message in status bar
-            UI.status.displayMessage("Panel " + (panelIndex + 1)
-                + ": Parse error in filter: " + ex.getMessage());
+            UI.status.displayMessage(getPanelNameForErrorMsg(panelMenuBar.getPanelName())
+                + ": " + ex.getMessage());
         }
     }
 
+    private String getPanelNameForErrorMsg(String panelName) {
+        if (panelName.equals("Panel")) {
```
Comment (dariusf) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Is there some default panel name constant that we can compare against here?

**Comment by dariusf** [comment]
Mostly just style issues. Also, needs to be updated to the latest master. You might want to squash away some of the extraneous commits, like things added in the course of review, things which should have been there to begin with, etc.

File: src/test/java/tests/FilterEvalTests.java [hunk 15]
```diff
@@ -37,6 +44,17 @@ public boolean matches(String filterExpr, TurboIssue issue) {
...
     }
 
+    /**
+     * Helper method for testing SemanticException thrown by different qualifiers
+     */
+    public void verifySemanticException(QualifierType type, String invalidInput) {
+        TurboIssue issue = new TurboIssue(REPO, 1, "");
+        thrown.expect(SemanticException.class);
+        thrown.expectMessage(String.format(SemanticException.ERR_MSG, type, 
+                type.getValidInputs()));
```
Comment (damithc) [inline src/test/java/tests/FilterEvalTests.java]: Line wrapping can be better, to show the nested relationship. e.g.
```java
thrown.expectMessage(
          String.format(SemanticException.ERR_MSG, type, type.getValidInputs()));
```

Comment (damithc) [inline src/test/java/tests/FilterEvalTests.java]: See line wrapping guidelines in this doc https://github.com/nus-cs2103/website/blob/master/contents/coding-standards-java.md

**Comment by jinified** [comment]
can review @dariusf

**Comment by dariusf** [comment]
Okay, no more comments from me.

File: src/main/java/filter/SemanticException.java [hunk 16]
```diff
@@ -0,0 +1,14 @@
+package filter;
+
+import filter.expression.QualifierType;
+
+@SuppressWarnings("serial")
+public class SemanticException extends FilterException {
```
Comment (damithc) [inline src/main/java/filter/SemanticException.java]: Write a header comment to explain the purpose of this class.

File: src/main/java/filter/SemanticException.java [hunk 17]
```diff
@@ -0,0 +1,14 @@
...
+    
+    public static final String ERROR_MESSAGE = "\"%s\" expects %s";
+    public SemanticException(QualifierType type, String details) {
+        super(String.format(ERROR_MESSAGE, type, details));
+        System.out.println(String.format(ERROR_MESSAGE, type, details));
```
Comment (damithc) [inline src/main/java/filter/SemanticException.java]: Is this intended?

File: src/main/java/filter/expression/QualifierType.java [hunk 18]
```diff
@@ -32,6 +33,30 @@
     }
 
     /**
+     * 
+     * Set valid inputs for each keyword except those that takes in any string
+     * @return
```
Comment (damithc) [inline src/main/java/filter/expression/QualifierType.java]: Incomplete comment

File: src/main/java/filter/expression/QualifierType.java [hunk 19]
```diff
@@ -32,6 +33,30 @@
...
+     */
+    private static Map<QualifierType, String> initialiseValidInputs() {
+        Map<QualifierType, String> validInputs = new HashMap<>();
```
Comment (damithc) [inline src/main/java/filter/expression/QualifierType.java]: To be precise, these are 'descriptions of valid input', not 'valid inputs'

File: src/main/java/filter/expression/QualifierType.java [hunk 20]
```diff
@@ -93,4 +118,15 @@ private static boolean isSpecialQualifier(String input) {
     public String toString() {
         return name().toLowerCase();
     }
+    
+    /**
+     * Retrieves acceptable inputs of a qualifier 
+     * @return
+     */
+    public String getValidInputs() {
```
Comment (damithc) [inline src/main/java/filter/expression/QualifierType.java]: Method name not precise enough.

File: src/main/java/filter/expression/QualifierType.java [hunk 21]
```diff
@@ -93,4 +118,15 @@ private static boolean isSpecialQualifier(String input) {
...
+        String defaultExpectedInput = "string";
+        if (VALID_INPUTS.containsKey(this)) return VALID_INPUTS.get(this);
+        return defaultExpectedInput;
```
Comment (damithc) [inline src/main/java/filter/expression/QualifierType.java]: Instead of having a Map defined and populated elsewhere, can't we use a switch statement inside this method. Seems this is the only place where that Map is used.

File: src/main/java/ui/issuepanel/FilterPanel.java [hunk 22]
```diff
@@ -179,12 +178,19 @@ private void applyStringFilter(String filterString) {
...
             this.applyFilterExpression(Qualifier.EMPTY);
             // Overrides message in status bar
-            UI.status.displayMessage("Panel " + (panelIndex + 1)
-                + ": Parse error in filter: " + ex.getMessage());
+            UI.status.displayMessage(getPanelNameForErrorMsg(panelMenuBar.getPanelName())
+                + ": " + ex.getMessage());
+        }
+    }
+
+    private String getPanelNameForErrorMsg(String panelName) {
```
Comment (damithc) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Don't define method names based on how the method is used.

File: src/main/java/filter/expression/QualifierType.java [hunk 23]
```diff
@@ -32,6 +32,20 @@
...
+    private static Map<QualifierType, String> initialiseDescriptionOfValidInputs() {
+        Map<QualifierType, String> validInputs = new HashMap<>();
+        
+        validInputs.put(IS, "\"open\", \"closed\", \"pr\", \"issue\", \"merged\","
+                + " \"read\", \"unread\", or \"unmerged\"");
+        validInputs.put(SORT, "\"comments\", \"repo\", \"updated\", \"id\", "
+                + " \"assignee\", label name, \"state\", or \"milestone\"");
+        return Collections.unmodifiableMap(validInputs);
+    }
+
```
Comment (damithc) [inline src/main/java/filter/expression/QualifierType.java]: Is this method uses somewhere?

File: src/main/java/ui/issuepanel/FilterPanel.java [hunk 24]
```diff
@@ -179,12 +178,19 @@ private void applyStringFilter(String filterString) {
...
             // Overrides message in status bar
-            UI.status.displayMessage("Panel " + (panelIndex + 1)
-                + ": Parse error in filter: " + ex.getMessage());
+            UI.status.displayMessage(resolvePanelInfo(panelMenuBar.getPanelName())
+                + ": " + ex.getMessage());
+        }
+    }
+
+    private String resolvePanelInfo(String panelName) {
+        if (panelName.equals("Panel")) {
```
Comment (damithc) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Magic string

File: src/main/java/ui/issuepanel/FilterPanel.java [hunk 25]
```diff
@@ -179,12 +178,19 @@ private void applyStringFilter(String filterString) {
...
             this.applyFilterExpression(Qualifier.EMPTY);
             // Overrides message in status bar
-            UI.status.displayMessage("Panel " + (panelIndex + 1)
-                + ": Parse error in filter: " + ex.getMessage());
+            UI.status.displayMessage(resolvePanelInfo(panelMenuBar.getPanelName())
+                + ": " + ex.getMessage());
+        }
+    }
+
+    private String resolvePanelInfo(String panelName) {
```
Comment (damithc) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Header comment for this method?

File: src/main/java/ui/issuepanel/FilterPanel.java (hunk 24 above)
Comment (jinified) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Should I add the a string constant to [PanelMenuBar.java](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/java/ui/components/PanelMenuBar.java#L43) where the panel name is initialized ?

Comment (damithc) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Sure.

File: src/test/java/tests/FilterEvalTests.java [hunk 26]
```diff
@@ -37,6 +44,17 @@ public boolean matches(String filterExpr, TurboIssue issue) {
         return Qualifier.process(empty, Parser.parse(filterExpr), issue);
     }
 
+    /**
+     * Helper method for testing SemanticException thrown by different qualifiers
+     */
```
Comment (damithc) [inline src/test/java/tests/FilterEvalTests.java]: Umm... not a very good description of the method. Write it is the form of `Does abc`. e.g. `Confirms that the the given input causes a SemanticException with the correct error message. Causes a test failure if it doesn't.`

Comment (damithc) [inline src/test/java/tests/FilterEvalTests.java]: When exactly is the expected exception is thrown. It's not clear from the method.

File: src/main/java/ui/issuepanel/FilterPanel.java [hunk 27]
```diff
@@ -179,12 +179,24 @@ private void applyStringFilter(String filterString) {
...
+            UI.status.displayMessage(resolvePanelName(panelMenuBar.getPanelName())
+                + ": " + ex.getMessage());
+        }
+    }
+
+    /**
+     * Shows panel name if renamed by user. Panel index is shown otherwise.
+     * @param panelName
+     * @return final panel name shown to users
+     */
```
Comment (damithc) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Still not clear what this method does (or why this method exists).

File: src/main/java/ui/issuepanel/FilterPanel.java [hunk 28]
```diff
@@ -179,12 +179,24 @@ private void applyStringFilter(String filterString) {
...
+    private String resolvePanelName(String panelName) {
+        if (panelName.equals(PanelMenuBar.DEFAULT_PANEL_NAME)) {
```
Comment (damithc) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Feels like `PanelMenuBar.DEFAULT_PANEL_NAME` should be a parameter to this method.

File: src/main/java/ui/issuepanel/FilterPanel.java [hunk 29]
```diff
@@ -179,12 +179,24 @@ private void applyStringFilter(String filterString) {
...
+            return PanelMenuBar.DEFAULT_PANEL_NAME + " " + (panelIndex + 1);
```
Comment (damithc) [inline src/main/java/ui/issuepanel/FilterPanel.java]: And this one `panelIndex`. Try to give all the "inputs" the method need as parameters. That makes the method signature more self explanatory.

File: src/main/java/filter/SemanticException.java [hunk 30]
```diff
@@ -0,0 +1,16 @@
...
+
+import filter.expression.QualifierType;
+
+/**
+ * Thrown to indicate an invalid input has been provided to a Qualifier
+ */
+@SuppressWarnings("serial")
+public class SemanticException extends FilterException {
+    
+    public static final String ERROR_MESSAGE = "\"%s\" expects %s";
```
Comment (damithc) [inline src/main/java/filter/SemanticException.java]: Add blank line here?

Comment (jinified) [inline src/main/java/filter/SemanticException.java]: After the class header comment ?

Comment (damithc) [inline src/main/java/filter/SemanticException.java]: Between the variable declaration and the method declaration.

Comment (jinified) [inline src/main/java/filter/SemanticException.java]: Seems like I already changed it on my local copy. Sorry for the confusion

**Comment by jinified** [comment]
review

File: src/main/java/filter/FilterException.java [hunk 31]
```diff
@@ -0,0 +1,8 @@
+package filter;
+
+@SuppressWarnings("serial")
```
Comment (dariusf) [inline src/main/java/filter/FilterException.java]: I guess we could document this as well, as being a general filter-related error. Maybe it should be abstract, so we ensure that something that's actually thrown has a concrete type/reason for happening?

File: src/main/java/filter/ParseException.java [hunk 32]
```diff
@@ -1,8 +1,11 @@
 package filter;
 
+/**
+ *  Thrown to indicate failure to interpret a filter expression
```
Comment (dariusf) [inline src/main/java/filter/ParseException.java]: "Failure to parse" might be a bit more precise. This exception indicates a problem with syntax.

File: src/main/java/filter/SemanticException.java [hunk 33]
```diff
@@ -0,0 +1,17 @@
+package filter;
+
+import filter.expression.QualifierType;
+
+/**
+ * Thrown to indicate an invalid input has been provided to a Qualifier
```
Comment (dariusf) [inline src/main/java/filter/SemanticException.java]: This is a little specific. It can indicate other sorts of failures when trying to interpret these expressions. Maybe write something along those lines (problems with interpretation), and give a few examples? "For example, invalid qualifier inputs, multiple qualifiers which should only appear once, etc."

File: src/main/java/filter/expression/QualifierType.java [hunk 34]
```diff
@@ -93,4 +93,32 @@ private static boolean isSpecialQualifier(String input) {
     public String toString() {
         return name().toLowerCase();
     }
+    
+    /**
+     * Retrieves acceptable inputs of a qualifier
```
Comment (dariusf) [inline src/main/java/filter/expression/QualifierType.java]: Maybe this could be something like: "returns a short description of the class of valid inputs a type of qualifier may be used with".

File: src/main/java/filter/expression/QualifierType.java [hunk 35]
```diff
@@ -93,4 +93,32 @@ private static boolean isSpecialQualifier(String input) {
...
+            case IN:
+                return "\"title\" or \"body\"";
+            case TYPE:
+                return "\"issue\" or \"pr\"";
+            case CREATED:
+                return "a date or a date range";
+            case REPO:
+                return "repo id";
+            default:
+                return "string";
```
Comment (dariusf) [inline src/main/java/filter/expression/QualifierType.java]: "a repo id", and "a string"?

File: src/main/java/ui/issuepanel/FilterPanel.java [hunk 36]
```diff
@@ -179,12 +179,26 @@ private void applyStringFilter(String filterString) {
...
+        }
+    }
+
+    /**
+     * Appends panel index to panel name if a panel is unnamed.
+     * This allows user to identify an otherwise unnamed panel.
+     * @param panelName
+     * @return final panel name shown to users
+     */
+    private String resolvePanelName(String panelName, String defaultName, int panelIndex) {
```
Comment (dariusf) [inline src/main/java/ui/issuepanel/FilterPanel.java]: Hmm, I'm not sure about these being parameters. They are all properties of the class that we're in. How about something like `getFriendlyName()`? Basically it returns a nice representation to be shown to users based on the panel's state.

Comment (jinified) [inline src/main/java/ui/issuepanel/FilterPanel.java]: I think removing the default name which is a constant and panelIndex which belongs to the class is fine. However, keeping the panelName as parameter because it is not a direct property of the class

Comment (dariusf) [inline src/main/java/ui/issuepanel/FilterPanel.java]: But it's transitively a property. :stuck_out_tongue: It can be accessed from there too.

**Comment by damithc** [comment]
Test methods don't follow the new naming convention, but we can correct it later.

**Comment by dariusf** [comment]
Almost there. Is the test coverage sufficient?

**Comment by jinified** [comment]
It did cover all possibilities.

**Comment by dariusf** [comment]
I mean, you should check coveralls and see where the drop is coming from.

**Comment by jinified** [comment]
The drop mainly comes from MenuControl class which is not related to this pr at all

**Comment by dariusf** [comment]
No idea why MenuControl was appearing earlier, but it seems like the drops are from the `in` and `repo` alias cases. Is it possible to cover them them now without too much effort? I know they aren't like the other qualifiers.

I don't think the FilterPanel parts are significant to test.

**Comment by jinified** [comment]
I already added test for `in` qualifier. I am not too sure about `repo` because technically it accepts any string and shouldn't throw any SemanticException. I don't we should write a test for `repo`.

**Comment by dariusf** [comment]
Hmm, there are no tests because they both don't throw semantic exceptions. Shouldn't they? If they didn't, we wouldn't need entries for them in `getDescriptionOfValidInputs`. Those cases are not covered because they aren't used.

On side note, just noticed that semantic exceptions are all created like so: `new SemanticException(type, type.getDescriptionOfValidInputs())`. If every qualifier type encapsulates the description of its inputs, we shouldn't need the second parameter.

Sorry for the last minute changes! We should sort out the coverage issues now, otherwise they'll never be fixed.

**Comment by jinified** [comment]
Haha it's ok. It is needed for `IN` but not for `REPO`, and the description is added for the sake of completion. Come to to think we can remove it until there is a use case for handling valid repo id

**Comment by dariusf** [comment]
Hmm, shouldn't we validate the repo id as well? Any string is permitted (given that repo aliases are coming), but other things like dates and ranges shouldn't be.

**Comment by jinified** [comment]
Because the way we parse `QualifierContent`, the `content` will only be assigned if it is a normal keyword. If i were to throw a SemanticException when the content is empty, it may also throw when there is no input which is supposed to be a ParseException.

**Comment by jinified** [comment]
Never mind I found a way to identify valid repo id by simply checking if the other fields are empty i.e `date`, `dateRange`, `number` and `numberRange`.

**Comment by dariusf** [comment]
What's an example where there's no input?

**Comment by jinified** [comment]
"repo:"

**Comment by dariusf** [comment]
Hmm, but doesn't that currently get caught before it ever gets to the content part? It will be a parse exception, yes, but it will happen even before the filter expression is evaluated.

**Comment by jinified** [comment]
Sorry my bad. You are right. Guess I will go ahead and throw the exception when the content is empty instead of returning false. Will need to change some of the tests for metaqualifier .

**Comment by dariusf** [comment]
Okay, no worries.

**Comment by jinified** [comment]
@dariusf  is it ok ?

File: src/main/java/filter/expression/Qualifier.java [hunk 37]
```diff
@@ -210,43 +212,60 @@ public boolean isSatisfiedBy(IModel model, TurboIssue issue, MetaQualifierInfo i
...
-        case UPDATED:
-            return satisfiesUpdatedHours(issue);
-        case REPO:
-            return satisfiesRepo(issue);
-        default:
-            assert false : "Missing case for " + type;
-            return false;
+            case ID :
+                return idSatisfies(issue);
+
```
Comment (dariusf) [inline src/main/java/filter/expression/Qualifier.java]: Hmm... do we use these whitespace conventions everywhere? We should follow the rest of the codebase, which is like how it was.

Comment (jinified) [inline src/main/java/filter/expression/Qualifier.java]: I changed it because it was mentioned in the coding guideline which follows the TEAMMARE guideline. So I thought it would be a good idea to follow it.  The whitespace is not common in the code base

**Comment by damithc** [comment]
Hmm... The space use in `switch` is inconsistent within the PR itself. Our coding standard says 

`case ID :` 

but I think that's an error in the standard itself. Should be `case ID:`?

**Comment by jinified** [comment]
actually it is more natural without the space after each case i.e `case ID:` which is also recommended by Google's Java guideline. But what do you think about the newline after each case ? I think the newline after each case is good to follow since it clearer this way.

**Comment by damithc** [comment]
Regarding the extra blank line above each `case`, while it makes the code look tidier, we are always trying to reduce vertical height (that's the the main reason why we don't align start and end braces). Extra blank lines can help to separate logical code blocks when all code is indented at the same level. However, each `case` is indented at a different level than the code that follows it, providing a visual break in the code even without the blank line. Therefore, we can do without the extra blank line.

**Comment by damithc** [comment]
Coding standard updated.

**Comment by jinified** [comment]
Reverted the changes. review please

File: src/main/java/filter/expression/Qualifier.java [hunk 38]
```diff
@@ -726,28 +732,28 @@ private boolean satisfiesCreationDate(TurboIssue issue) {
...
-            assert issue.getAssignee() != null;
-            return issue.getAssignee().isPresent();
-        default:
-            return false;
+            case "label":
+            case "labels":
+                return issue.getLabels().size() > 0;
+            case "milestone":
+            case "milestones":
+            case "m" :
```
Comment (damithc) [inline src/main/java/filter/expression/Qualifier.java]: extra space before `:`. Noticed it in a few other places too.

File: src/test/java/tests/FilterEvalTests.java [hunk 39]
```diff
@@ -726,4 +755,24 @@ public void filterLabelMatching() {
         assertFalse(Qualifier.labelMatches("pi.hi", "p.high"));
         assertFalse(Qualifier.labelMatches(".", "p.high"));
     }
+
+    /**
+     * Helper method for testing an issue against a filter string in the context
+     * of an empty model.
+     */
```
Comment (damithc) [inline src/test/java/tests/FilterEvalTests.java]: Follow the same style when commenting. e.g. ~~`Helper method for testing `~~ `Confirms that ...`

**Comment by damithc** [comment]
@jinified 
Some cosmetic changes requested. 
While you are at it, can you remove the indentation of `case` clauses again?. I know it was it our previous coding standard, but the common convention seems to align `case` to `switch` which makes sense because it is just like an if-else-if statement.
I updated the coding standard.
@dariusf can merge after above is fixed. no further approval needed.

**Comment by dariusf** [comment]
:tada:

**Comment by jinified** [comment]
lol
